CREATE OR REPLACE VIEW VW_DADOSREGRESSAO_ITEM
	AS
		SELECT
			  B.ITEM_IDITEM AS ID_ITEM, C.NM_ITEM AS NM_ITEM,
			  EXTRACT(MONTH FROM B.DT_REALIZADA) AS MES_NUM,
        CASE 
          WHEN EXTRACT(MONTH FROM (DT_REALIZADA)) = 1 THEN 'Jan'
          WHEN EXTRACT(MONTH FROM (DT_REALIZADA)) = 2 THEN 'Fev'
          WHEN EXTRACT(MONTH FROM (DT_REALIZADA)) = 3 THEN 'Mar'
          WHEN EXTRACT(MONTH FROM (DT_REALIZADA)) = 4 THEN 'Abr'
          WHEN EXTRACT(MONTH FROM (DT_REALIZADA)) = 5 THEN 'Mai'
          WHEN EXTRACT(MONTH FROM (DT_REALIZADA)) = 6 THEN 'Jun'
          WHEN EXTRACT(MONTH FROM (DT_REALIZADA)) = 7 THEN 'Jul'
          WHEN EXTRACT(MONTH FROM (DT_REALIZADA)) = 8 THEN 'Ago'
          WHEN EXTRACT(MONTH FROM (DT_REALIZADA)) = 9 THEN 'Set'
          WHEN EXTRACT(MONTH FROM (DT_REALIZADA)) = 10 THEN 'Out'
          WHEN EXTRACT(MONTH FROM (DT_REALIZADA)) = 11 THEN 'Nov'
          WHEN EXTRACT(MONTH FROM (DT_REALIZADA)) = 12 THEN 'Dez'
        END MES_DESC,    
        EXTRACT(YEAR FROM B.DT_REALIZADA) AS ANO,
				SUM(B.QUANTFATURAMENTO) AS TOTAL_FAT_MES,SUM(B.QUANTCLIENTE) AS TOTAL_CLI_MES,
			  TRUNC(REGR_AVGY(SUM(B.QUANTFATURAMENTO),EXTRACT(MONTH FROM B.DT_REALIZADA)) 
				  OVER (ORDER BY EXTRACT(YEAR FROM B.DT_REALIZADA),EXTRACT(MONTH FROM B.DT_REALIZADA),B.ITEM_IDITEM),2) AS REGRESSAO_VALOR_FAT_MES,
			  TRUNC(REGR_AVGY(SUM(B.QUANTCLIENTE),EXTRACT(MONTH FROM B.DT_REALIZADA)) 
				  OVER (ORDER BY EXTRACT(YEAR FROM B.DT_REALIZADA),EXTRACT(MONTH FROM B.DT_REALIZADA),B.ITEM_IDITEM),2) AS REGRESSAO_VALOR_CLI_MES
	    FROM CARGA_DADOS B
		INNER JOIN ITEM C ON B.ITEM_IDITEM = C.ID_ITEM
		WHERE B.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-5),'MONTH') AS DIA FROM CARGA_DADOS)
		GROUP BY B.ITEM_IDITEM,C.NM_ITEM,EXTRACT(MONTH FROM B.DT_REALIZADA),EXTRACT(YEAR FROM B.DT_REALIZADA)
		ORDER BY EXTRACT(YEAR FROM B.DT_REALIZADA),EXTRACT(MONTH FROM B.DT_REALIZADA)



