CREATE OR REPLACE VIEW VW_DADOSREGRESSAO_GRUPO
	AS
		SELECT
			  D.ID_TIPO_CLASSE AS ID_GRUPO, D.DESC_CLASSE AS NM_GRUPO,
			  EXTRACT(MONTH FROM B.DT_REALIZADA) AS MES,EXTRACT(YEAR FROM B.DT_REALIZADA) AS ANO,
				SUM(B.QUANTFATURAMENTO) AS TOTAL_FAT_MES,SUM(B.QUANTCLIENTE) AS TOTAL_CLI_MES,
			  TRUNC(REGR_AVGY(SUM(B.QUANTFATURAMENTO),EXTRACT(MONTH FROM B.DT_REALIZADA)) 
				  OVER (ORDER BY EXTRACT(YEAR FROM B.DT_REALIZADA),EXTRACT(MONTH FROM B.DT_REALIZADA),D.ID_TIPO_CLASSE),2) AS REGRESSAO_VALOR_FAT_MES,
			  TRUNC(REGR_AVGY(SUM(B.QUANTCLIENTE),EXTRACT(MONTH FROM B.DT_REALIZADA)) 
				  OVER (ORDER BY EXTRACT(YEAR FROM B.DT_REALIZADA),EXTRACT(MONTH FROM B.DT_REALIZADA),D.ID_TIPO_CLASSE),2) AS REGRESSAO_VALOR_CLI_MES
	    FROM CARGA_DADOS B
		INNER JOIN ITEM C ON B.ITEM_IDITEM = C.ID_ITEM
		INNER JOIN TIPOCLASSE D ON D.ID_TIPO_CLASSE = C.CLASSE_IDTIPO
		WHERE B.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-5),'MONTH') AS DIA FROM CARGA_DADOS)
		GROUP BY D.ID_TIPO_CLASSE,D.DESC_CLASSE,EXTRACT(MONTH FROM B.DT_REALIZADA),EXTRACT(YEAR FROM B.DT_REALIZADA)
		ORDER BY EXTRACT(YEAR FROM B.DT_REALIZADA),EXTRACT(MONTH FROM B.DT_REALIZADA)