	CREATE OR REPLACE VIEW VW_PESOTOTALMES_PORITEM
		AS		  
		  SELECT
			  A.ID_ITEM AS IDITEM,A.NOME_ITEM AS NMITEM,
			  (A.CENARIOPROVAVELFAT * B.PESO_MEDIO) AS PESOFAT,
			  (A.CENARIOPROVAVELCLI * B.PESO_MEDIO) AS PESOCLI,
			  A.MESFUTURO AS MES,
			  CASE 
				 WHEN A.MESFUTURO = 1 THEN 'Jan'
				 WHEN A.MESFUTURO = 2 THEN 'Fev'
				 WHEN A.MESFUTURO = 3 THEN 'Mar'
				 WHEN A.MESFUTURO = 4 THEN 'Abr'
				 WHEN A.MESFUTURO = 5 THEN 'Mai'
				 WHEN A.MESFUTURO = 6 THEN 'Jun'
				 WHEN A.MESFUTURO = 7 THEN 'Jul'
				 WHEN A.MESFUTURO = 8 THEN 'Ago'
				 WHEN A.MESFUTURO = 9 THEN 'Set'
				 WHEN A.MESFUTURO = 10 THEN 'Out'
				 WHEN A.MESFUTURO = 11 THEN 'Nov'
				 WHEN A.MESFUTURO = 12 THEN 'Dez'
			   END MES_DESC,  
			   A.ANOFUTURO AS ANO  
		  FROM DADOS_FUTUROS_ITEM A
		  INNER JOIN ITEM B ON A.ID_ITEM = B.ID_ITEM
		  WHERE A.TIPO_PROCESSAMENTO =  2

		  UNION

		  SELECT
			A.ITEM_IDITEM AS IDITEM,
			B.NM_ITEM AS NMITEM,
			(SUM (A.QUANTFATURAMENTO) * B.PESO_MEDIO) AS PESOFAT,
			(SUM (A.QUANTCLIENTE) * B.PESO_MEDIO) AS PESOCLI,
			EXTRACT(MONTH FROM A.DT_REALIZADA) AS MES,
			CASE 
				WHEN EXTRACT(MONTH FROM (A.DT_REALIZADA)) = 1 THEN 'Jan'
				WHEN EXTRACT(MONTH FROM (A.DT_REALIZADA)) = 2 THEN 'Fev'
				WHEN EXTRACT(MONTH FROM (A.DT_REALIZADA)) = 3 THEN 'Mar'
				WHEN EXTRACT(MONTH FROM (A.DT_REALIZADA)) = 4 THEN 'Abr'
				WHEN EXTRACT(MONTH FROM (A.DT_REALIZADA)) = 5 THEN 'Mai'
				WHEN EXTRACT(MONTH FROM (A.DT_REALIZADA)) = 6 THEN 'Jun'
				WHEN EXTRACT(MONTH FROM (A.DT_REALIZADA)) = 7 THEN 'Jul'
				WHEN EXTRACT(MONTH FROM (A.DT_REALIZADA)) = 8 THEN 'Ago'
				WHEN EXTRACT(MONTH FROM (A.DT_REALIZADA)) = 9 THEN 'Set'
				WHEN EXTRACT(MONTH FROM (A.DT_REALIZADA)) = 10 THEN 'Out'
				WHEN EXTRACT(MONTH FROM (A.DT_REALIZADA)) = 11 THEN 'Nov'
				WHEN EXTRACT(MONTH FROM (A.DT_REALIZADA)) = 12 THEN 'Dez'
			END MES_DESC,  
			EXTRACT(YEAR FROM A.DT_REALIZADA) AS ANO        
		  FROM CARGA_DADOS A
		  INNER JOIN ITEM B ON A.ITEM_IDITEM = B.ID_ITEM
		  WHERE A.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-5),'MONTH') AS DIA FROM CARGA_DADOS)
		  GROUP BY A.ITEM_IDITEM, B.NM_ITEM,EXTRACT(YEAR FROM A.DT_REALIZADA),EXTRACT(MONTH FROM A.DT_REALIZADA),B.PESO_MEDIO

