CREATE OR REPLACE VIEW VW_TOTFATECLIENTE_PORGRUPO
   AS   
      SELECT
        C.ID_TIPO_CLASSE AS COD_CLASSE,
        C.DESC_CLASSE AS NM_CLASSE,
        EXTRACT(MONTH FROM A.DT_REALIZADA) AS MES_NUM,
        CASE 
            WHEN EXTRACT(MONTH FROM (A.DT_REALIZADA)) = 1 THEN 'Jan'
            WHEN EXTRACT(MONTH FROM (A.DT_REALIZADA)) = 2 THEN 'Fev'
            WHEN EXTRACT(MONTH FROM (A.DT_REALIZADA)) = 3 THEN 'Mar'
            WHEN EXTRACT(MONTH FROM (A.DT_REALIZADA)) = 4 THEN 'Abr'
            WHEN EXTRACT(MONTH FROM (A.DT_REALIZADA)) = 5 THEN 'Mai'
            WHEN EXTRACT(MONTH FROM (A.DT_REALIZADA)) = 6 THEN 'Jun'
            WHEN EXTRACT(MONTH FROM (A.DT_REALIZADA)) = 7 THEN 'Jul'
            WHEN EXTRACT(MONTH FROM (A.DT_REALIZADA)) = 8 THEN 'Ago'
            WHEN EXTRACT(MONTH FROM (A.DT_REALIZADA)) = 9 THEN 'Set'
            WHEN EXTRACT(MONTH FROM (A.DT_REALIZADA)) = 10 THEN 'Out'
            WHEN EXTRACT(MONTH FROM (A.DT_REALIZADA)) = 11 THEN 'Nov'
            WHEN EXTRACT(MONTH FROM (A.DT_REALIZADA)) = 12 THEN 'Dez'
        END MES_DESC,  
        EXTRACT(YEAR FROM A.DT_REALIZADA) AS ANO,
        SUM (A.QUANTFATURAMENTO) AS TOTALFATURADO,
        SUM (A.QUANTCLIENTE) AS TOTALCLIENTE
      FROM CARGA_DADOS A
      INNER JOIN ITEM B ON A.ITEM_IDITEM = B.ID_ITEM
      INNER JOIN TIPOCLASSE C ON B.CLASSE_IDTIPO = C.ID_TIPO_CLASSE
      WHERE A.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-5),'MONTH') AS DIA FROM CARGA_DADOS)
      GROUP BY C.ID_TIPO_CLASSE,C.DESC_CLASSE,EXTRACT(YEAR FROM A.DT_REALIZADA),EXTRACT(MONTH FROM A.DT_REALIZADA)
      ORDER BY EXTRACT(YEAR FROM A.DT_REALIZADA),EXTRACT(MONTH FROM A.DT_REALIZADA)