CREATE OR REPLACE PROCEDURE SP_PROCESSADADOSITEM_TODOS (VALORPARAMETRO IN INT) AS
      BEGIN
	     DECLARE 
		    --------------------------------------- Variaveis da Primeira Lista ----------
			------------------------------------------------------------------------------
			IDITEM INT;
			NOMEITEM VARCHAR (100);
			QTDTOTCLIENTEMES FLOAT;
			TOTALCLIENTE FLOAT;
			VARIACAOCLI FLOAT;
			TOTALFATURAMENTO FLOAT;
			VARIACAOFAT FLOAT;
			MESVARIADO INT;
			ANOVARIADO INT;
			CENARIOTIMISTACLIENTE FLOAT;
			CENARIOPESSIMISTACLIENTE FLOAT;
			MESFUTURO INT;
			ANOFUTURO INT;			
			CENARIOTIMISTAFATURAMENTO FLOAT;
			CENARIOPESSIMISTAFATURAMENTO FLOAT;
			VOLUMEPROVAVELFAT FLOAT;
			VOLUMEPROVAVELCLI FLOAT;
			--------------------------------------- Variaveis da Segunda Lista ----------
			------------------------------------------------------------------------------
			IDITEM01 INT;
			NOMEITEM01 VARCHAR (100);
			QTDTOTCLIENTEMES01 FLOAT;
			TOTALCLIENTE01 FLOAT;
			VARIACAOCLI01 FLOAT;
			TOTALFATURAMENTO01 FLOAT;
			VARIACAOFAT01 FLOAT;
			MESVARIADO01 INT;
			ANOVARIADO01 INT;			
			CENARIOTIMISTACLIENTE01 FLOAT;
			CENARIOPESSIMISTACLIENTE01 FLOAT;
			MESFUTURO01 INT;
			ANOFUTURO01 INT;			
			CENARIOTIMISTAFATURAMENTO01 FLOAT;
			CENARIOPESSIMISTAFATURAMENTO01 FLOAT;
			VOLUMEPROVAVELFAT01 FLOAT;
			VOLUMEPROVAVELCLI01 FLOAT;
			---------------------------------------- Fim das Variaveis da Segunda Lista ----
			--------------------------------------------------------------------------------
			CONTADOR NUMBER := 0;
			TOTALCONT NUMBER;
			MESINSERIDO NUMBER := 0;
			ANOINSERIDO NUMBER := 0;
			CURSOR LISTA IS (SELECT ITEM,NOMEITEM,QTDTOTCLIENTEMES,TOTALCLIENTE,VARIACAOCLI,TOTALFATURAMENTO,VARIACAOFAT,
							MES,ANO,CENARIOTIMISTACLIENTE,CENARIOPESSIMISTACLIENTE,MESFUTURO,ANOFUTURO,CENARIOTIMISTAFATURAMENTO,
							CENARIOPESSIMISTAFATURAMENTO,VOLUMEPROVAVELFAT,VOLUMEPROVAVELCLI FROM
							(SELECT A.ITEM_IDITEM AS ITEM,B.NM_ITEM AS NOMEITEM,SUM(A.QUANTCLIENTE) AS QTDTOTCLIENTEMES,
							(SELECT SUM (B.QUANTCLIENTE) FROM CARGA_DADOS B WHERE A.ITEM_IDITEM = B.ITEM_IDITEM 
							 AND B.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-VALORPARAMETRO+1),'MONTH') AS DIA FROM CARGA_DADOS)) AS TOTALCLIENTE,
							EXTRACT(MONTH FROM A.DT_REALIZADA) AS MES,EXTRACT(YEAR FROM A.DT_REALIZADA) AS ANO,
							TRUNC(((SUM(A.QUANTCLIENTE)/(SELECT SUM (B.QUANTCLIENTE) FROM CARGA_DADOS B WHERE A.ITEM_IDITEM = B.ITEM_IDITEM
							AND B.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-VALORPARAMETRO+1),'MONTH') AS DIA FROM CARGA_DADOS)))*100),2) AS VARIACAOCLI,
							SUM(A.QUANTFATURAMENTO) AS QTDTOTFATURAMENTOMES,
							(SELECT SUM (B.QUANTFATURAMENTO) FROM CARGA_DADOS B WHERE A.ITEM_IDITEM = B.ITEM_IDITEM  
							AND B.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-VALORPARAMETRO+1),'MONTH') AS DIA FROM CARGA_DADOS)) AS TOTALFATURAMENTO,
							TRUNC(((SUM(A.QUANTFATURAMENTO)/(SELECT SUM (B.QUANTFATURAMENTO) FROM CARGA_DADOS B WHERE A.ITEM_IDITEM = B.ITEM_IDITEM
							AND B.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-VALORPARAMETRO+1),'MONTH') AS DIA FROM CARGA_DADOS)))*100),2) AS VARIACAOFAT,
							TRUNC(((((SELECT MAX(VARIACAO) FROM (SELECT A.ITEM_IDITEM AS ITEM,
							TRUNC(((SUM(A.QUANTCLIENTE)/(SELECT SUM (B.QUANTCLIENTE) FROM CARGA_DADOS B WHERE A.ITEM_IDITEM = B.ITEM_IDITEM 
							AND B.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-VALORPARAMETRO+1),'MONTH') AS DIA FROM CARGA_DADOS)))*100),2) AS VARIACAO
							FROM CARGA_DADOS A
							GROUP BY A.ITEM_IDITEM, EXTRACT(MONTH FROM A.DT_REALIZADA),EXTRACT(YEAR FROM A.DT_REALIZADA)) WHERE ITEM = A.ITEM_IDITEM)
							*
							(SELECT SUM (G.QUANTCLIENTE) FROM CARGA_DADOS G
							WHERE EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
							AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
							AND G.ITEM_IDITEM = A.ITEM_IDITEM))/100) 
							+
							(SELECT SUM (G.QUANTCLIENTE) FROM CARGA_DADOS G
							WHERE EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
							AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
							AND G.ITEM_IDITEM = A.ITEM_IDITEM)),0) AS CENARIOTIMISTACLIENTE,
							TRUNC(((((SELECT MIN(VARIACAO) FROM (SELECT A.ITEM_IDITEM AS ITEM,
							TRUNC(((SUM(A.QUANTCLIENTE)/(SELECT SUM (B.QUANTCLIENTE) FROM CARGA_DADOS B WHERE A.ITEM_IDITEM = B.ITEM_IDITEM
							AND B.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-VALORPARAMETRO+1),'MONTH') AS DIA FROM CARGA_DADOS)))*100),2) AS VARIACAO
							FROM CARGA_DADOS A
							GROUP BY A.ITEM_IDITEM, EXTRACT(MONTH FROM A.DT_REALIZADA),EXTRACT(YEAR FROM A.DT_REALIZADA)) WHERE ITEM = A.ITEM_IDITEM)
							*
							(SELECT SUM (G.QUANTCLIENTE) FROM CARGA_DADOS G
							WHERE EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
							AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
							AND G.ITEM_IDITEM = A.ITEM_IDITEM))/100) 
							+
							(SELECT SUM (G.QUANTCLIENTE) FROM CARGA_DADOS G
							WHERE EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
							AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
							AND G.ITEM_IDITEM = A.ITEM_IDITEM)),0) AS CENARIOPESSIMISTACLIENTE,
							EXTRACT (MONTH FROM (SELECT ADD_MONTHS(MAX(AA.DT_REALIZADA),1) FROM CARGA_DADOS AA WHERE AA.ITEM_IDITEM = A.ITEM_IDITEM)) AS MESFUTURO,
							EXTRACT (YEAR FROM (SELECT ADD_MONTHS(MAX(AA.DT_REALIZADA),1) FROM CARGA_DADOS AA WHERE AA.ITEM_IDITEM = A.ITEM_IDITEM)) AS ANOFUTURO,
							TRUNC(((((SELECT MAX(VARIACAO) FROM (SELECT A.ITEM_IDITEM AS ITEM,
							TRUNC(((SUM(A.QUANTFATURAMENTO)/(SELECT SUM (B.QUANTFATURAMENTO) FROM CARGA_DADOS B WHERE A.ITEM_IDITEM = B.ITEM_IDITEM
							AND B.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-VALORPARAMETRO+1),'MONTH') AS DIA FROM CARGA_DADOS)))*100),2) AS VARIACAO
							FROM CARGA_DADOS A
							GROUP BY A.ITEM_IDITEM, EXTRACT(MONTH FROM A.DT_REALIZADA),EXTRACT(YEAR FROM A.DT_REALIZADA)) WHERE ITEM = A.ITEM_IDITEM)
							*
							(SELECT SUM (G.QUANTFATURAMENTO) FROM CARGA_DADOS G
							WHERE EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
							AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
							AND G.ITEM_IDITEM = A.ITEM_IDITEM))/100) 
							+
							(SELECT SUM (G.QUANTFATURAMENTO) FROM CARGA_DADOS G
							WHERE EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
							AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
							AND G.ITEM_IDITEM = A.ITEM_IDITEM)),0) AS CENARIOTIMISTAFATURAMENTO,
							TRUNC(((((SELECT MIN(VARIACAO) FROM (SELECT A.ITEM_IDITEM AS ITEM,
							TRUNC(((SUM(A.QUANTFATURAMENTO)/(SELECT SUM (B.QUANTFATURAMENTO) FROM CARGA_DADOS B WHERE A.ITEM_IDITEM = B.ITEM_IDITEM
							AND B.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-VALORPARAMETRO+1),'MONTH') AS DIA FROM CARGA_DADOS)))*100),2) AS VARIACAO
							FROM CARGA_DADOS A
							GROUP BY A.ITEM_IDITEM, EXTRACT(MONTH FROM A.DT_REALIZADA),EXTRACT(YEAR FROM A.DT_REALIZADA)) WHERE ITEM = A.ITEM_IDITEM)
							*
							(SELECT SUM (G.QUANTFATURAMENTO) FROM CARGA_DADOS G
							WHERE EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
							AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
							AND G.ITEM_IDITEM = A.ITEM_IDITEM))/100) 
							+
							(SELECT SUM (G.QUANTFATURAMENTO) FROM CARGA_DADOS G
							WHERE EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
							AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
							AND G.ITEM_IDITEM = A.ITEM_IDITEM)),0) AS CENARIOPESSIMISTAFATURAMENTO,
							
							TRUNC((((((SELECT
							TRUNC(((SUM(D.QUANTFATURAMENTO)/(SELECT SUM (B.QUANTFATURAMENTO) FROM CARGA_DADOS B WHERE D.ITEM_IDITEM = B.ITEM_IDITEM
							AND B.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-VALORPARAMETRO+1),'MONTH') AS DIA FROM CARGA_DADOS)))*100),2) AS VARIACAO  
							FROM CARGA_DADOS D
							WHERE D.ITEM_IDITEM = A.ITEM_IDITEM
							AND EXTRACT (YEAR FROM D.DT_REALIZADA) = (SELECT MAX (ANO) FROM (SELECT EXTRACT (YEAR FROM C.DT_REALIZADA) AS ANO FROM CARGA_DADOS C))
							AND EXTRACT (MONTH FROM D.DT_REALIZADA) = (SELECT MAX (MES) FROM (SELECT EXTRACT (MONTH FROM C.DT_REALIZADA) AS MES FROM CARGA_DADOS C
																	   WHERE EXTRACT (YEAR FROM C.DT_REALIZADA) = (SELECT MAX (ANO) FROM (SELECT EXTRACT (YEAR FROM C.DT_REALIZADA) AS ANO FROM CARGA_DADOS C))))
							GROUP BY D.ITEM_IDITEM, EXTRACT(MONTH FROM D.DT_REALIZADA),EXTRACT(YEAR FROM D.DT_REALIZADA))
							*
							(SELECT SUM (G.QUANTFATURAMENTO) FROM CARGA_DADOS G
							WHERE EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
							AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
							AND G.ITEM_IDITEM = A.ITEM_IDITEM))/100) 
							+
							(SELECT SUM (G.QUANTFATURAMENTO) FROM CARGA_DADOS G
							WHERE EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
							AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
							AND G.ITEM_IDITEM = A.ITEM_IDITEM))),0) AS VOLUMEPROVAVELFAT,
							TRUNC((((((SELECT
							TRUNC(((SUM(D.QUANTCLIENTE)/(SELECT SUM (B.QUANTCLIENTE) FROM CARGA_DADOS B WHERE D.ITEM_IDITEM = B.ITEM_IDITEM
							AND B.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-VALORPARAMETRO+1),'MONTH') AS DIA FROM CARGA_DADOS)))*100),2) AS VARIACAO  
							FROM CARGA_DADOS D
							WHERE D.ITEM_IDITEM = A.ITEM_IDITEM
							AND EXTRACT (YEAR FROM D.DT_REALIZADA) = (SELECT MAX (ANO) FROM (SELECT EXTRACT (YEAR FROM C.DT_REALIZADA) AS ANO FROM CARGA_DADOS C))
							AND EXTRACT (MONTH FROM D.DT_REALIZADA) = (SELECT MAX (MES) FROM (SELECT EXTRACT (MONTH FROM C.DT_REALIZADA) AS MES FROM CARGA_DADOS C
																	   WHERE EXTRACT (YEAR FROM C.DT_REALIZADA) = (SELECT MAX (ANO) FROM (SELECT EXTRACT (YEAR FROM C.DT_REALIZADA) AS ANO FROM CARGA_DADOS C))))
							GROUP BY D.ITEM_IDITEM, EXTRACT(MONTH FROM D.DT_REALIZADA),EXTRACT(YEAR FROM D.DT_REALIZADA))
							*
							(SELECT SUM (G.QUANTCLIENTE) FROM CARGA_DADOS G
							WHERE EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
							AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
							AND G.ITEM_IDITEM = A.ITEM_IDITEM))/100) 
							+
							(SELECT SUM (G.QUANTCLIENTE) FROM CARGA_DADOS G
							WHERE EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
							AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
							AND G.ITEM_IDITEM = A.ITEM_IDITEM))),0) AS VOLUMEPROVAVELCLI  					
							

							FROM CARGA_DADOS A 
							INNER JOIN ITEM B ON A.ITEM_IDITEM = B.ID_ITEM
							WHERE A.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-VALORPARAMETRO+1),'MONTH') AS DIA FROM CARGA_DADOS)							 
							GROUP BY A.ITEM_IDITEM,B.NM_ITEM,EXTRACT(MONTH FROM A.DT_REALIZADA),EXTRACT(YEAR FROM A.DT_REALIZADA)
							ORDER BY 1,6,5)				
							
							WHERE VARIACAOCLI = (SELECT MAX(VARIACAO) FROM (SELECT A.ITEM_IDITEM AS ITEMD,
							TRUNC(((SUM(A.QUANTCLIENTE)/(SELECT SUM (B.QUANTCLIENTE) FROM CARGA_DADOS B WHERE A.ITEM_IDITEM = B.ITEM_IDITEM 
							AND B.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-VALORPARAMETRO+1),'MONTH') AS DIA FROM CARGA_DADOS)))*100),2) AS VARIACAO
							FROM CARGA_DADOS A GROUP BY A.ITEM_IDITEM, EXTRACT(MONTH FROM A.DT_REALIZADA),EXTRACT(YEAR FROM A.DT_REALIZADA)) WHERE ITEMD = ITEM));
							
		
		CURSOR LISTA02 IS (SELECT ITEM,NOMEITEM,QTDTOTCLIENTEMES,TOTALCLIENTE,VARIACAOCLI,TOTALFATURAMENTO,VARIACAOFAT,
						   MES,ANO,CENARIOTIMISTACLIENTE,CENARIOPESSIMISTACLIENTE,MESFUTURO,ANOFUTURO,CENARIOTIMISTAFATURAMENTO,
						   CENARIOPESSIMISTAFATURAMENTO,VOLUMEPROVAVELFAT,VOLUMEPROVAVELCLI FROM
							(SELECT
								A.ITEM_IDITEM AS ITEM,B.NM_ITEM AS NOMEITEM,SUM(A.QUANTCLIENTE) AS QTDTOTCLIENTEMES,
								(SELECT SUM (B.QUANTCLIENTE) FROM CARGA_DADOS B WHERE A.ITEM_IDITEM = B.ITEM_IDITEM 
									AND B.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-VALORPARAMETRO+1),'MONTH') AS DIA FROM CARGA_DADOS)
								AND EXTRACT(DAY FROM B.DT_REALIZADA) BETWEEN 1 AND 15) AS TOTALCLIENTE,
								EXTRACT(MONTH FROM A.DT_REALIZADA) AS MES,EXTRACT(YEAR FROM A.DT_REALIZADA) AS ANO,
								TRUNC(((SUM(A.QUANTCLIENTE)/(SELECT SUM (B.QUANTCLIENTE) FROM CARGA_DADOS B WHERE A.ITEM_IDITEM = B.ITEM_IDITEM
								AND B.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-VALORPARAMETRO+1),'MONTH') AS DIA FROM CARGA_DADOS)
								AND EXTRACT(DAY FROM B.DT_REALIZADA) BETWEEN 1 AND 15))*100),2) AS VARIACAOCLI,
								SUM(A.QUANTFATURAMENTO) AS QTDTOTFATURAMENTOMES,
								(SELECT SUM (B.QUANTFATURAMENTO) FROM CARGA_DADOS B WHERE A.ITEM_IDITEM = B.ITEM_IDITEM  
								AND B.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-VALORPARAMETRO+1),'MONTH') AS DIA FROM CARGA_DADOS)
								AND EXTRACT(DAY FROM B.DT_REALIZADA) BETWEEN 1 AND 15) AS TOTALFATURAMENTO,
								TRUNC(((SUM(A.QUANTFATURAMENTO)/(SELECT SUM (B.QUANTFATURAMENTO) FROM CARGA_DADOS B WHERE A.ITEM_IDITEM = B.ITEM_IDITEM
								AND B.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-VALORPARAMETRO+1),'MONTH') AS DIA FROM CARGA_DADOS)
								AND EXTRACT(DAY FROM B.DT_REALIZADA) BETWEEN 1 AND 15))*100),2) AS VARIACAOFAT,
								TRUNC(((((SELECT MAX(VARIACAO) FROM (SELECT A.ITEM_IDITEM AS ITEM,    
								TRUNC(((SUM(A.QUANTCLIENTE)/(SELECT SUM (B.QUANTCLIENTE) FROM CARGA_DADOS B WHERE A.ITEM_IDITEM = B.ITEM_IDITEM 
								AND B.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-VALORPARAMETRO+1),'MONTH') AS DIA FROM CARGA_DADOS)
								AND EXTRACT(DAY FROM B.DT_REALIZADA) BETWEEN 1 AND 15))*100),2) AS VARIACAO
								FROM CARGA_DADOS A
								WHERE EXTRACT(DAY FROM A.DT_REALIZADA)BETWEEN 1 AND 15
								GROUP BY A.ITEM_IDITEM, EXTRACT(MONTH FROM A.DT_REALIZADA),EXTRACT(YEAR FROM A.DT_REALIZADA)) WHERE ITEM = A.ITEM_IDITEM)
								*
								(SELECT SUM (G.QUANTCLIENTE) FROM CARGA_DADOS G
								WHERE EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
								AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
								AND G.ITEM_IDITEM = A.ITEM_IDITEM
								AND EXTRACT(DAY FROM G.DT_REALIZADA) BETWEEN 1 AND 15))/100) 
								+
								(SELECT SUM (G.QUANTCLIENTE) FROM CARGA_DADOS G
								WHERE EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
								AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
								AND EXTRACT(DAY FROM G.DT_REALIZADA) BETWEEN 1 AND 15
								AND G.ITEM_IDITEM = A.ITEM_IDITEM)),0) AS CENARIOTIMISTACLIENTE,
								TRUNC(((((SELECT MIN(VARIACAO) FROM (SELECT A.ITEM_IDITEM AS ITEM,
								TRUNC(((SUM(A.QUANTCLIENTE)/(SELECT SUM (B.QUANTCLIENTE) FROM CARGA_DADOS B WHERE A.ITEM_IDITEM = B.ITEM_IDITEM
									AND B.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-VALORPARAMETRO+1),'MONTH') AS DIA FROM CARGA_DADOS)
								AND EXTRACT(DAY FROM B.DT_REALIZADA) BETWEEN 1 AND 15))*100),2) AS VARIACAO
									FROM CARGA_DADOS A
								WHERE EXTRACT(DAY FROM A.DT_REALIZADA)BETWEEN 1 AND 15
									GROUP BY A.ITEM_IDITEM, EXTRACT(MONTH FROM A.DT_REALIZADA),EXTRACT(YEAR FROM A.DT_REALIZADA)) WHERE ITEM = A.ITEM_IDITEM)
									*
								 (SELECT SUM (G.QUANTCLIENTE) FROM CARGA_DADOS G
								  WHERE EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
									AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
								AND EXTRACT(DAY FROM G.DT_REALIZADA) BETWEEN 1 AND 15
									AND G.ITEM_IDITEM = A.ITEM_IDITEM))/100) 
									+
									(SELECT SUM (G.QUANTCLIENTE) FROM CARGA_DADOS G
									WHERE EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
									AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
								AND EXTRACT(DAY FROM G.DT_REALIZADA) BETWEEN 1 AND 15
									AND G.ITEM_IDITEM = A.ITEM_IDITEM)),0) AS CENARIOPESSIMISTACLIENTE,
								EXTRACT (MONTH FROM (SELECT ADD_MONTHS(MAX(AA.DT_REALIZADA),1) FROM CARGA_DADOS AA WHERE AA.ITEM_IDITEM = A.ITEM_IDITEM)) AS MESFUTURO,
								EXTRACT (YEAR FROM (SELECT ADD_MONTHS(MAX(AA.DT_REALIZADA),1) FROM CARGA_DADOS AA WHERE AA.ITEM_IDITEM = A.ITEM_IDITEM)) AS ANOFUTURO,
								TRUNC(((((SELECT MAX(VARIACAO) FROM (SELECT A.ITEM_IDITEM AS ITEM,
								TRUNC(((SUM(A.QUANTFATURAMENTO)/(SELECT SUM (B.QUANTFATURAMENTO) FROM CARGA_DADOS B WHERE A.ITEM_IDITEM = B.ITEM_IDITEM
								AND B.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-VALORPARAMETRO+1),'MONTH') AS DIA FROM CARGA_DADOS)
								AND EXTRACT(DAY FROM B.DT_REALIZADA) BETWEEN 1 AND 15))*100),2) AS VARIACAO
								FROM CARGA_DADOS A
								WHERE EXTRACT(DAY FROM A.DT_REALIZADA) BETWEEN 1 AND 15
								GROUP BY A.ITEM_IDITEM, EXTRACT(MONTH FROM A.DT_REALIZADA),EXTRACT(YEAR FROM A.DT_REALIZADA)) WHERE ITEM = A.ITEM_IDITEM)
								*
								(SELECT SUM (G.QUANTFATURAMENTO) FROM CARGA_DADOS G
								WHERE EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
								AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
								AND EXTRACT(DAY FROM G.DT_REALIZADA) BETWEEN 1 AND 15
								AND G.ITEM_IDITEM = A.ITEM_IDITEM))/100) 
								+
								(SELECT SUM (G.QUANTFATURAMENTO) FROM CARGA_DADOS G
								WHERE EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
								AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
								AND EXTRACT(DAY FROM G.DT_REALIZADA) BETWEEN 1 AND 15
								AND G.ITEM_IDITEM = A.ITEM_IDITEM)),0) AS CENARIOTIMISTAFATURAMENTO,
								TRUNC(((((SELECT MIN(VARIACAO) FROM (SELECT A.ITEM_IDITEM AS ITEM,
								TRUNC(((SUM(A.QUANTFATURAMENTO)/(SELECT SUM (B.QUANTFATURAMENTO) FROM CARGA_DADOS B WHERE A.ITEM_IDITEM = B.ITEM_IDITEM
								AND B.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-VALORPARAMETRO+1),'MONTH') AS DIA FROM CARGA_DADOS)
								AND EXTRACT(DAY FROM B.DT_REALIZADA) BETWEEN 1 AND 15))*100),2) AS VARIACAO
								FROM CARGA_DADOS A
								WHERE EXTRACT(DAY FROM A.DT_REALIZADA) BETWEEN 1 AND 15
								GROUP BY A.ITEM_IDITEM, EXTRACT(MONTH FROM A.DT_REALIZADA),EXTRACT(YEAR FROM A.DT_REALIZADA)) WHERE ITEM = A.ITEM_IDITEM)
								*
								(SELECT SUM (G.QUANTFATURAMENTO) FROM CARGA_DADOS G
								WHERE EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
								AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
								AND EXTRACT(DAY FROM G.DT_REALIZADA) BETWEEN 1 AND 15
								AND G.ITEM_IDITEM = A.ITEM_IDITEM))/100) 
								+
								(SELECT SUM (G.QUANTFATURAMENTO) FROM CARGA_DADOS G
								WHERE EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
								AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
								AND EXTRACT(DAY FROM G.DT_REALIZADA) BETWEEN 1 AND 15
								AND G.ITEM_IDITEM = A.ITEM_IDITEM)),0) AS CENARIOPESSIMISTAFATURAMENTO,
								TRUNC((((((SELECT
								TRUNC(((SUM(D.QUANTFATURAMENTO)/(SELECT SUM (B.QUANTFATURAMENTO) FROM CARGA_DADOS B WHERE D.ITEM_IDITEM = B.ITEM_IDITEM
								AND B.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-VALORPARAMETRO+1),'MONTH') AS DIA FROM CARGA_DADOS)
								AND EXTRACT(DAY FROM B.DT_REALIZADA) BETWEEN 1 AND 15))*100),2) AS VARIACAO  
								FROM CARGA_DADOS D
								WHERE EXTRACT(DAY FROM D.DT_REALIZADA) BETWEEN 1 AND 15
								AND D.ITEM_IDITEM = A.ITEM_IDITEM
								AND EXTRACT (YEAR FROM D.DT_REALIZADA) = (SELECT MAX (ANO) FROM (SELECT EXTRACT (YEAR FROM C.DT_REALIZADA) AS ANO FROM CARGA_DADOS C))
								AND EXTRACT (MONTH FROM D.DT_REALIZADA) = (SELECT MAX (MES) FROM (SELECT EXTRACT (MONTH FROM C.DT_REALIZADA) AS MES FROM CARGA_DADOS C
																			WHERE EXTRACT (YEAR FROM C.DT_REALIZADA) = (SELECT MAX (ANO) FROM (SELECT EXTRACT (YEAR FROM C.DT_REALIZADA) AS ANO FROM CARGA_DADOS C))))
								GROUP BY D.ITEM_IDITEM, EXTRACT(MONTH FROM D.DT_REALIZADA),EXTRACT(YEAR FROM D.DT_REALIZADA))
								*
								(SELECT SUM (G.QUANTFATURAMENTO) FROM CARGA_DADOS G
								WHERE EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
								AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
								AND EXTRACT(DAY FROM G.DT_REALIZADA) BETWEEN 1 AND 15
								AND G.ITEM_IDITEM = A.ITEM_IDITEM))/100) 
								+
								(SELECT SUM (G.QUANTFATURAMENTO) FROM CARGA_DADOS G
								WHERE EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
								AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
								AND EXTRACT(DAY FROM G.DT_REALIZADA) BETWEEN 1 AND 15
								AND G.ITEM_IDITEM = A.ITEM_IDITEM))),0) AS VOLUMEPROVAVELFAT,
								TRUNC((((((SELECT
								TRUNC(((SUM(D.QUANTCLIENTE)/(SELECT SUM (B.QUANTCLIENTE) FROM CARGA_DADOS B WHERE D.ITEM_IDITEM = B.ITEM_IDITEM
								AND B.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-VALORPARAMETRO+1),'MONTH') AS DIA FROM CARGA_DADOS)
								AND EXTRACT(DAY FROM B.DT_REALIZADA) BETWEEN 1 AND 15))*100),2) AS VARIACAO  
								FROM CARGA_DADOS D
								WHERE EXTRACT(DAY FROM D.DT_REALIZADA) BETWEEN 1 AND 15
								AND D.ITEM_IDITEM = A.ITEM_IDITEM
								AND EXTRACT (YEAR FROM D.DT_REALIZADA) = (SELECT MAX (ANO) FROM (SELECT EXTRACT (YEAR FROM C.DT_REALIZADA) AS ANO FROM CARGA_DADOS C))
								AND EXTRACT (MONTH FROM D.DT_REALIZADA) = (SELECT MAX (MES) FROM (SELECT EXTRACT (MONTH FROM C.DT_REALIZADA) AS MES FROM CARGA_DADOS C
																			WHERE EXTRACT (YEAR FROM C.DT_REALIZADA) = (SELECT MAX (ANO) FROM (SELECT EXTRACT (YEAR FROM C.DT_REALIZADA) AS ANO FROM CARGA_DADOS C))))
								GROUP BY D.ITEM_IDITEM, EXTRACT(MONTH FROM D.DT_REALIZADA),EXTRACT(YEAR FROM D.DT_REALIZADA))
								*
								(SELECT SUM (G.QUANTCLIENTE) FROM CARGA_DADOS G
								WHERE EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
								AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
								AND EXTRACT(DAY FROM G.DT_REALIZADA) BETWEEN 1 AND 15
								AND G.ITEM_IDITEM = A.ITEM_IDITEM))/100) 
								+
								(SELECT SUM (G.QUANTCLIENTE) FROM CARGA_DADOS G
								WHERE EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
								AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
								AND EXTRACT(DAY FROM G.DT_REALIZADA) BETWEEN 1 AND 15
								AND G.ITEM_IDITEM = A.ITEM_IDITEM))),0) AS VOLUMEPROVAVELCLI    
								
								FROM CARGA_DADOS A
								INNER JOIN ITEM B ON A.ITEM_IDITEM = B.ID_ITEM
								WHERE A.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-VALORPARAMETRO+1),'MONTH') AS DIA FROM CARGA_DADOS)
								AND EXTRACT(DAY FROM A.DT_REALIZADA) BETWEEN 1 AND 15
								GROUP BY A.ITEM_IDITEM,B.NM_ITEM,EXTRACT(MONTH FROM A.DT_REALIZADA),EXTRACT(YEAR FROM A.DT_REALIZADA)
								ORDER BY 1,6,5)

								WHERE VARIACAOCLI = (SELECT MAX(VARIACAO) FROM (SELECT A.ITEM_IDITEM AS ITEMD,
								TRUNC(((SUM(A.QUANTCLIENTE)/(SELECT SUM (B.QUANTCLIENTE) FROM CARGA_DADOS B WHERE A.ITEM_IDITEM = B.ITEM_IDITEM 
								AND B.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-VALORPARAMETRO+1),'MONTH') AS DIA FROM CARGA_DADOS)
								AND EXTRACT(DAY FROM B.DT_REALIZADA) BETWEEN 1 AND 15))*100),2) AS VARIACAO
								FROM CARGA_DADOS A 
								WHERE EXTRACT(DAY FROM A.DT_REALIZADA) BETWEEN 1 AND 15
								GROUP BY A.ITEM_IDITEM, EXTRACT(MONTH FROM A.DT_REALIZADA),EXTRACT(YEAR FROM A.DT_REALIZADA)) WHERE ITEMD = ITEM));						
							
			BEGIN
                SELECT COUNT(*) INTO TOTALCONT FROM (SELECT A.ITEM_IDITEM FROM CARGA_DADOS A GROUP BY A.ITEM_IDITEM);
				SELECT COALESCE(MES,0) INTO MESINSERIDO FROM (SELECT MAX(MESFUTURO) AS MES FROM DADOS_FUTUROS_ITEM);
				SELECT COALESCE(ANO,0) INTO ANOINSERIDO FROM (SELECT MAX(ANOFUTURO) AS ANO FROM DADOS_FUTUROS_ITEM);				
				DBMS_OUTPUT.ENABLE (100000000);				
				OPEN LISTA;				
				FETCH LISTA INTO IDITEM,NOMEITEM,QTDTOTCLIENTEMES,TOTALCLIENTE,VARIACAOCLI,TOTALFATURAMENTO,VARIACAOFAT,
				MESVARIADO,ANOVARIADO,CENARIOTIMISTACLIENTE,CENARIOPESSIMISTACLIENTE,MESFUTURO,ANOFUTURO,CENARIOTIMISTAFATURAMENTO,
				CENARIOPESSIMISTAFATURAMENTO,VOLUMEPROVAVELFAT,VOLUMEPROVAVELCLI;
				OPEN LISTA02;
				FETCH LISTA02 INTO IDITEM01,NOMEITEM01,QTDTOTCLIENTEMES01,TOTALCLIENTE01,VARIACAOCLI01,TOTALFATURAMENTO01,VARIACAOFAT01,
				MESVARIADO01,ANOVARIADO01,CENARIOTIMISTACLIENTE01,CENARIOPESSIMISTACLIENTE01,MESFUTURO01,ANOFUTURO01,CENARIOTIMISTAFATURAMENTO01,
				CENARIOPESSIMISTAFATURAMENTO01,VOLUMEPROVAVELFAT01,VOLUMEPROVAVELCLI01;			
				
				
				WHILE CONTADOR < TOTALCONT
					LOOP 			
						 IF (MESFUTURO <> MESINSERIDO AND ANOFUTURO <> ANOINSERIDO) THEN
								CONTADOR := CONTADOR + 1;
								INSERT INTO DADOS_FUTUROS_ITEM (ID_DADOS_FUTUROS_ITEM,ID_ITEM,NOME_ITEM,QTDTOTCLIENTEMES,TOTALCLIENTE,VARIACAOCLI,
								TOTALFATURAMENTO,VARIACAOFAT,MESVARIADO,ANOVARIADO,CENARIOTIMISTACLIENTE,CENARIOPESSIMISTACLIENTE,MESFUTURO,
								ANOFUTURO,CENARIOTIMISTAFATURAMENTO,CENARIOPESSIMISTAFATURAMENTO,CENARIOPROVAVELFAT,CENARIOPROVAVELCLI,TIPO_PROCESSAMENTO,
								DATAPROCESSAMENTO,ITEM_REPROCESSADO)
								VALUES (IDDADOSFUTUROSITEM.NEXTVAL,IDITEM,NOMEITEM,QTDTOTCLIENTEMES,TOTALCLIENTE,VARIACAOCLI,TOTALFATURAMENTO,VARIACAOFAT,
								MESVARIADO,ANOVARIADO,CENARIOTIMISTACLIENTE,CENARIOPESSIMISTACLIENTE,MESFUTURO,ANOFUTURO,CENARIOTIMISTAFATURAMENTO,
								CENARIOPESSIMISTAFATURAMENTO,VOLUMEPROVAVELFAT,VOLUMEPROVAVELCLI,2,(SELECT TO_CHAR (SYSDATE,'DD/MM/YYYY HH24:MM:SS') FROM DUAL),'N');						
								FETCH LISTA INTO IDITEM,NOMEITEM,QTDTOTCLIENTEMES,TOTALCLIENTE,VARIACAOCLI,TOTALFATURAMENTO,VARIACAOFAT,
								MESVARIADO,ANOVARIADO,CENARIOTIMISTACLIENTE,CENARIOPESSIMISTACLIENTE,MESFUTURO,ANOFUTURO,CENARIOTIMISTAFATURAMENTO,
								CENARIOPESSIMISTAFATURAMENTO,VOLUMEPROVAVELFAT,VOLUMEPROVAVELCLI;

								INSERT INTO DADOS_FUTUROS_ITEM (ID_DADOS_FUTUROS_ITEM,ID_ITEM,NOME_ITEM,QTDTOTCLIENTEMES,TOTALCLIENTE,VARIACAOCLI,
								TOTALFATURAMENTO,VARIACAOFAT,MESVARIADO,ANOVARIADO,CENARIOTIMISTACLIENTE,CENARIOPESSIMISTACLIENTE,MESFUTURO,
								ANOFUTURO,CENARIOTIMISTAFATURAMENTO,CENARIOPESSIMISTAFATURAMENTO,CENARIOPROVAVELFAT,CENARIOPROVAVELCLI,TIPO_PROCESSAMENTO,
								DATAPROCESSAMENTO,ITEM_REPROCESSADO)
								VALUES (IDDADOSFUTUROSITEM.NEXTVAL,IDITEM01,NOMEITEM01,QTDTOTCLIENTEMES01,TOTALCLIENTE01,VARIACAOCLI01,TOTALFATURAMENTO01,VARIACAOFAT01,
								MESVARIADO01,ANOVARIADO01,CENARIOTIMISTACLIENTE01,CENARIOPESSIMISTACLIENTE01,MESFUTURO01,ANOFUTURO01,CENARIOTIMISTAFATURAMENTO01,
								CENARIOPESSIMISTAFATURAMENTO01,VOLUMEPROVAVELFAT01,VOLUMEPROVAVELCLI01,1,(SELECT TO_CHAR (SYSDATE,'DD/MM/YYYY HH24:MM:SS') FROM DUAL),'N');						
								FETCH LISTA02 INTO IDITEM01,NOMEITEM01,QTDTOTCLIENTEMES01,TOTALCLIENTE01,VARIACAOCLI01,TOTALFATURAMENTO01,VARIACAOFAT01,
								MESVARIADO01,ANOVARIADO01,CENARIOTIMISTACLIENTE01,CENARIOPESSIMISTACLIENTE01,MESFUTURO01,ANOFUTURO01,CENARIOTIMISTAFATURAMENTO01,
								CENARIOPESSIMISTAFATURAMENTO01,VOLUMEPROVAVELFAT01,VOLUMEPROVAVELCLI01;	
								
						 ELSE
								CONTADOR := CONTADOR + 1;
								INSERT INTO DADOS_FUTUROS_ITEM (ID_DADOS_FUTUROS_ITEM,ID_ITEM,NOME_ITEM,QTDTOTCLIENTEMES,TOTALCLIENTE,VARIACAOCLI,
								TOTALFATURAMENTO,VARIACAOFAT,MESVARIADO,ANOVARIADO,CENARIOTIMISTACLIENTE,CENARIOPESSIMISTACLIENTE,MESFUTURO,
								ANOFUTURO,CENARIOTIMISTAFATURAMENTO,CENARIOPESSIMISTAFATURAMENTO,CENARIOPROVAVELFAT,CENARIOPROVAVELCLI,TIPO_PROCESSAMENTO,
								DATAPROCESSAMENTO,ITEM_REPROCESSADO)
								VALUES (IDDADOSFUTUROSITEM.NEXTVAL,IDITEM,NOMEITEM,QTDTOTCLIENTEMES,TOTALCLIENTE,VARIACAOCLI,TOTALFATURAMENTO,VARIACAOFAT,
								MESVARIADO,ANOVARIADO,CENARIOTIMISTACLIENTE,CENARIOPESSIMISTACLIENTE,MESFUTURO,ANOFUTURO,CENARIOTIMISTAFATURAMENTO,
								CENARIOPESSIMISTAFATURAMENTO,VOLUMEPROVAVELFAT,VOLUMEPROVAVELCLI,2,(SELECT TO_CHAR (SYSDATE,'DD/MM/YYYY HH24:MM:SS') FROM DUAL),'S');						
								FETCH LISTA INTO IDITEM,NOMEITEM,QTDTOTCLIENTEMES,TOTALCLIENTE,VARIACAOCLI,TOTALFATURAMENTO,VARIACAOFAT,
								MESVARIADO,ANOVARIADO,CENARIOTIMISTACLIENTE,CENARIOPESSIMISTACLIENTE,MESFUTURO,ANOFUTURO,CENARIOTIMISTAFATURAMENTO,
								CENARIOPESSIMISTAFATURAMENTO,VOLUMEPROVAVELFAT,VOLUMEPROVAVELCLI;	
								
								INSERT INTO DADOS_FUTUROS_ITEM (ID_DADOS_FUTUROS_ITEM,ID_ITEM,NOME_ITEM,QTDTOTCLIENTEMES,TOTALCLIENTE,VARIACAOCLI,
								TOTALFATURAMENTO,VARIACAOFAT,MESVARIADO,ANOVARIADO,CENARIOTIMISTACLIENTE,CENARIOPESSIMISTACLIENTE,MESFUTURO,
								ANOFUTURO,CENARIOTIMISTAFATURAMENTO,CENARIOPESSIMISTAFATURAMENTO,CENARIOPROVAVELFAT,CENARIOPROVAVELCLI,TIPO_PROCESSAMENTO,
								DATAPROCESSAMENTO,ITEM_REPROCESSADO)
								VALUES (IDDADOSFUTUROSITEM.NEXTVAL,IDITEM01,NOMEITEM01,QTDTOTCLIENTEMES01,TOTALCLIENTE01,VARIACAOCLI01,TOTALFATURAMENTO01,VARIACAOFAT01,
								MESVARIADO01,ANOVARIADO01,CENARIOTIMISTACLIENTE01,CENARIOPESSIMISTACLIENTE01,MESFUTURO01,ANOFUTURO01,CENARIOTIMISTAFATURAMENTO01,
								CENARIOPESSIMISTAFATURAMENTO01,VOLUMEPROVAVELFAT01,VOLUMEPROVAVELCLI01,1,(SELECT TO_CHAR (SYSDATE,'DD/MM/YYYY HH24:MM:SS') FROM DUAL),'S');						
								FETCH LISTA02 INTO IDITEM01,NOMEITEM01,QTDTOTCLIENTEMES01,TOTALCLIENTE01,VARIACAOCLI01,TOTALFATURAMENTO01,VARIACAOFAT01,
								MESVARIADO01,ANOVARIADO01,CENARIOTIMISTACLIENTE01,CENARIOPESSIMISTACLIENTE01,MESFUTURO01,ANOFUTURO01,CENARIOTIMISTAFATURAMENTO01,
								CENARIOPESSIMISTAFATURAMENTO01,VOLUMEPROVAVELFAT01,VOLUMEPROVAVELCLI01;	
						 END IF;
					END LOOP;
				CLOSE LISTA;
				CLOSE LISTA02;
			END;
	   END;


