CREATE OR REPLACE PROCEDURE SP_PROCESSADADOSITEM_TODOS AS
      BEGIN
	     DECLARE 
			IDITEM INT;
			NOMEITEM VARCHAR (100);
			QTDTOTCLIENTEMES FLOAT;
			TOTALCLIENTE FLOAT;
			VARIACAOCLI FLOAT;
			TOTALFATURAMENTO FLOAT;
			VARIACAOFAT FLOAT;
			MESVARIADO INT;
			ANOVARIADO INT;
			CENARIOTIMISTACLIENTE FLOAT;
			CENARIOPESSIMISTACLIENTE FLOAT;
			MESFUTURO INT;
			ANOFUTURO INT;			
			CENARIOTIMISTAFATURAMENTO FLOAT;
			CENARIOPESSIMISTAFATURAMENTO FLOAT;
			CONTADOR NUMBER := 0;
			TOTALCONT NUMBER;
			MESINSERIDO NUMBER := 0;
			ANOINSERIDO NUMBER := 0;
			CURSOR LISTA IS (SELECT ITEM,NOMEITEM,QTDTOTCLIENTEMES,TOTALCLIENTE,VARIACAOCLI,TOTALFATURAMENTO,VARIACAOFAT,
							MES,ANO,CENARIOTIMISTACLIENTE,CENARIOPESSIMISTACLIENTE,MESFUTURO,ANOFUTURO,CENARIOTIMISTAFATURAMENTO,
							CENARIOPESSIMISTAFATURAMENTO FROM
							(SELECT A.ITEM_IDITEM AS ITEM,B.NM_ITEM AS NOMEITEM,SUM(A.QUANTCLIENTE) AS QTDTOTCLIENTEMES,
							(SELECT SUM (B.QUANTCLIENTE) FROM CARGA_DADOS B WHERE A.ITEM_IDITEM = B.ITEM_IDITEM) AS TOTALCLIENTE,
							EXTRACT(MONTH FROM A.DT_REALIZADA) AS MES,EXTRACT(YEAR FROM A.DT_REALIZADA) AS ANO,
							TRUNC(((SUM(A.QUANTCLIENTE)/(SELECT SUM (B.QUANTCLIENTE) FROM CARGA_DADOS B WHERE A.ITEM_IDITEM = B.ITEM_IDITEM))*100),2) AS VARIACAOCLI,
							SUM(A.QUANTFATURAMENTO) AS QTDTOTFATURAMENTOMES,
							(SELECT SUM (B.QUANTFATURAMENTO) FROM CARGA_DADOS B WHERE A.ITEM_IDITEM = B.ITEM_IDITEM) AS TOTALFATURAMENTO,
							TRUNC(((SUM(A.QUANTFATURAMENTO)/(SELECT SUM (B.QUANTFATURAMENTO) FROM CARGA_DADOS B WHERE A.ITEM_IDITEM = B.ITEM_IDITEM))*100),2) AS VARIACAOFAT,
							TRUNC(((((SELECT MAX(VARIACAO) FROM (SELECT A.ITEM_IDITEM AS ITEM,
							TRUNC(((SUM(A.QUANTCLIENTE)/(SELECT SUM (B.QUANTCLIENTE) FROM CARGA_DADOS B WHERE A.ITEM_IDITEM = B.ITEM_IDITEM))*100),2) AS VARIACAO
							FROM CARGA_DADOS A
							GROUP BY A.ITEM_IDITEM, EXTRACT(MONTH FROM A.DT_REALIZADA),EXTRACT(YEAR FROM A.DT_REALIZADA)) WHERE ITEM = A.ITEM_IDITEM)
							*
							(SELECT SUM (G.QUANTCLIENTE) FROM CARGA_DADOS G
							WHERE EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
							AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
							AND G.ITEM_IDITEM = A.ITEM_IDITEM))/100) 
							+
							(SELECT SUM (G.QUANTCLIENTE) FROM CARGA_DADOS G
							WHERE EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
							AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
							AND G.ITEM_IDITEM = A.ITEM_IDITEM)),0) AS CENARIOTIMISTACLIENTE,
							TRUNC(((((SELECT MIN(VARIACAO) FROM (SELECT A.ITEM_IDITEM AS ITEM,
							TRUNC(((SUM(A.QUANTCLIENTE)/(SELECT SUM (B.QUANTCLIENTE) FROM CARGA_DADOS B WHERE A.ITEM_IDITEM = B.ITEM_IDITEM))*100),2) AS VARIACAO
							FROM CARGA_DADOS A
							GROUP BY A.ITEM_IDITEM, EXTRACT(MONTH FROM A.DT_REALIZADA),EXTRACT(YEAR FROM A.DT_REALIZADA)) WHERE ITEM = A.ITEM_IDITEM)
							*
							(SELECT SUM (G.QUANTCLIENTE) FROM CARGA_DADOS G
							WHERE EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
							AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
							AND G.ITEM_IDITEM = A.ITEM_IDITEM))/100) 
							+
							(SELECT SUM (G.QUANTCLIENTE) FROM CARGA_DADOS G
							WHERE EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
							AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
							AND G.ITEM_IDITEM = A.ITEM_IDITEM)),0) AS CENARIOPESSIMISTACLIENTE,
							EXTRACT (MONTH FROM (SELECT ADD_MONTHS(MAX(AA.DT_REALIZADA),1) FROM CARGA_DADOS AA WHERE AA.ITEM_IDITEM = A.ITEM_IDITEM)) AS MESFUTURO,
							EXTRACT (YEAR FROM (SELECT ADD_MONTHS(MAX(AA.DT_REALIZADA),1) FROM CARGA_DADOS AA WHERE AA.ITEM_IDITEM = A.ITEM_IDITEM)) AS ANOFUTURO,
							TRUNC(((((SELECT MAX(VARIACAO) FROM (SELECT A.ITEM_IDITEM AS ITEM,
							TRUNC(((SUM(A.QUANTFATURAMENTO)/(SELECT SUM (B.QUANTFATURAMENTO) FROM CARGA_DADOS B WHERE A.ITEM_IDITEM = B.ITEM_IDITEM))*100),2) AS VARIACAO
							FROM CARGA_DADOS A
							GROUP BY A.ITEM_IDITEM, EXTRACT(MONTH FROM A.DT_REALIZADA),EXTRACT(YEAR FROM A.DT_REALIZADA)) WHERE ITEM = A.ITEM_IDITEM)
							*
							(SELECT SUM (G.QUANTFATURAMENTO) FROM CARGA_DADOS G
							WHERE EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
							AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
							AND G.ITEM_IDITEM = A.ITEM_IDITEM))/100) 
							+
							(SELECT SUM (G.QUANTFATURAMENTO) FROM CARGA_DADOS G
							WHERE EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
							AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
							AND G.ITEM_IDITEM = A.ITEM_IDITEM)),0) AS CENARIOTIMISTAFATURAMENTO,
							TRUNC(((((SELECT MIN(VARIACAO) FROM (SELECT A.ITEM_IDITEM AS ITEM,
							TRUNC(((SUM(A.QUANTFATURAMENTO)/(SELECT SUM (B.QUANTFATURAMENTO) FROM CARGA_DADOS B WHERE A.ITEM_IDITEM = B.ITEM_IDITEM))*100),2) AS VARIACAO
							FROM CARGA_DADOS A
							GROUP BY A.ITEM_IDITEM, EXTRACT(MONTH FROM A.DT_REALIZADA),EXTRACT(YEAR FROM A.DT_REALIZADA)) WHERE ITEM = A.ITEM_IDITEM)
							*
							(SELECT SUM (G.QUANTFATURAMENTO) FROM CARGA_DADOS G
							WHERE EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
							AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
							AND G.ITEM_IDITEM = A.ITEM_IDITEM))/100) 
							+
							(SELECT SUM (G.QUANTFATURAMENTO) FROM CARGA_DADOS G
							WHERE EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
							AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E WHERE E.ITEM_IDITEM = A.ITEM_IDITEM)
							AND G.ITEM_IDITEM = A.ITEM_IDITEM)),0) AS CENARIOPESSIMISTAFATURAMENTO

							FROM CARGA_DADOS A 
							INNER JOIN ITEM B ON A.ITEM_IDITEM = B.ID_ITEM
							GROUP BY A.ITEM_IDITEM,B.NM_ITEM,EXTRACT(MONTH FROM A.DT_REALIZADA),EXTRACT(YEAR FROM A.DT_REALIZADA)
							ORDER BY 1,6,5)
							WHERE VARIACAOCLI = (SELECT MAX(VARIACAO) FROM (SELECT A.ITEM_IDITEM AS ITEMD,
							TRUNC(((SUM(A.QUANTCLIENTE)/(SELECT SUM (B.QUANTCLIENTE) FROM CARGA_DADOS B WHERE A.ITEM_IDITEM = B.ITEM_IDITEM))*100),2) AS VARIACAO
							FROM CARGA_DADOS A GROUP BY A.ITEM_IDITEM, EXTRACT(MONTH FROM A.DT_REALIZADA),EXTRACT(YEAR FROM A.DT_REALIZADA)) WHERE ITEMD = ITEM));
			BEGIN
                SELECT COUNT(*) INTO TOTALCONT FROM (SELECT A.ITEM_IDITEM FROM CARGA_DADOS A GROUP BY A.ITEM_IDITEM);
				SELECT COALESCE(MES,0) INTO MESINSERIDO FROM (SELECT MAX(MESFUTURO) AS MES FROM DADOS_FUTUROS_ITEM);
				SELECT COALESCE(ANO,0) INTO ANOINSERIDO FROM (SELECT MAX(ANOFUTURO) AS ANO FROM DADOS_FUTUROS_ITEM);				
				DBMS_OUTPUT.ENABLE (100000000);				
				OPEN LISTA;				
				FETCH LISTA INTO IDITEM,NOMEITEM,QTDTOTCLIENTEMES,TOTALCLIENTE,VARIACAOCLI,TOTALFATURAMENTO,VARIACAOFAT,
				MESVARIADO,ANOVARIADO,CENARIOTIMISTACLIENTE,CENARIOPESSIMISTACLIENTE,MESFUTURO,ANOFUTURO,CENARIOTIMISTAFATURAMENTO,
				CENARIOPESSIMISTAFATURAMENTO;
				WHILE CONTADOR < TOTALCONT
					LOOP 			
						 IF (MESFUTURO <> MESINSERIDO AND ANOFUTURO <> ANOINSERIDO) THEN
								CONTADOR := CONTADOR + 1;
								INSERT INTO DADOS_FUTUROS_ITEM (ID_DADOS_FUTUROS_ITEM,ID_ITEM,NOME_ITEM,QTDTOTCLIENTEMES,TOTALCLIENTE,VARIACAOCLI,
								TOTALFATURAMENTO,VARIACAOFAT,MESVARIADO,ANOVARIADO,CENARIOTIMISTACLIENTE,CENARIOPESSIMISTACLIENTE,MESFUTURO,
								ANOFUTURO,CENARIOTIMISTAFATURAMENTO,CENARIOPESSIMISTAFATURAMENTO) VALUES (IDDADOSFUTUROSITEM.NEXTVAL,IDITEM,NOMEITEM,
								QTDTOTCLIENTEMES,TOTALCLIENTE,VARIACAOCLI,TOTALFATURAMENTO,VARIACAOFAT,MESVARIADO,ANOVARIADO,CENARIOTIMISTACLIENTE,
								CENARIOPESSIMISTACLIENTE,MESFUTURO,ANOFUTURO,CENARIOTIMISTAFATURAMENTO,CENARIOPESSIMISTAFATURAMENTO);						
								FETCH LISTA INTO IDITEM,NOMEITEM,QTDTOTCLIENTEMES,TOTALCLIENTE,VARIACAOCLI,TOTALFATURAMENTO,VARIACAOFAT,
								MESVARIADO,ANOVARIADO,CENARIOTIMISTACLIENTE,CENARIOPESSIMISTACLIENTE,MESFUTURO,ANOFUTURO,CENARIOTIMISTAFATURAMENTO,
								CENARIOPESSIMISTAFATURAMENTO;	
						 ELSE
								CLOSE LISTA;
							    RETURN;
						 END IF;
					END LOOP;
				CLOSE LISTA;
			END;
	   END;


