CREATE OR REPLACE PROCEDURE SP_PROCESSADADOSGRUPO_TODOS (VALORPARAMETRO IN INT) AS
      BEGIN
	     DECLARE 
			------------------------------------------------ Variaveis da Lista por 30 Dias ------
			--------------------------------------------------------------------------------------		 
			IDITEM INT;
			NOMEITEM VARCHAR (100);
			QTDTOTCLIENTEMES FLOAT;
			TOTALCLIENTE FLOAT;
			VARIACAOCLI FLOAT;
			TOTALFATURAMENTO FLOAT;
			VARIACAOFAT FLOAT;
			MESVARIADO INT;
			ANOVARIADO INT;
			CENARIOTIMISTACLIENTE FLOAT;
			CENARIOPESSIMISTACLIENTE FLOAT;
			MESFUTURO INT;
			ANOFUTURO INT;			
			CENARIOTIMISTAFATURAMENTO FLOAT;
			CENARIOPESSIMISTAFATURAMENTO FLOAT;
			CENARIOPROVAVELFAT FLOAT;
			CENARIOPROVAVELCLI FLOAT;
			----------------------------------------------- Variaveis da Lista por 15 Dias ---------
			----------------------------------------------------------------------------------------
			IDITEM01 INT;
			NOMEITEM01 VARCHAR (100);
			QTDTOTCLIENTEMES01 FLOAT;
			TOTALCLIENTE01 FLOAT;
			VARIACAOCLI01 FLOAT;
			TOTALFATURAMENTO01 FLOAT;
			VARIACAOFAT01 FLOAT;
			MESVARIADO01 INT;
			ANOVARIADO01 INT;
			CENARIOTIMISTACLIENTE01 FLOAT;
			CENARIOPESSIMISTACLIENTE01 FLOAT;
			MESFUTURO01 INT;
			ANOFUTURO01 INT;			
			CENARIOTIMISTAFATURAMENTO01 FLOAT;
			CENARIOPESSIMISTAFATURAMENTO01 FLOAT;
			CENARIOPROVAVELFAT01 FLOAT;
			CENARIOPROVAVELCLI01 FLOAT;
			------------------------------------------------- Fim da Declarção das Variaveis dos Cursores ------
			----------------------------------------------------------------------------------------------------
			CONTADOR NUMBER := 0;
			TOTALCONT NUMBER;
			MESINSERIDO NUMBER := 0;
			ANOINSERIDO NUMBER := 0;
			CURSOR LISTA IS (SELECT IDCLASSE,NOMECLASSE,QTDTOTCLIENTEMES,TOTALCLIENTE,VARIACAOCLI,TOTALFATURAMENTO,VARIACAOFAT,
							 MES,ANO,CENARIOTIMISTACLIENTE,CENARIOPESSIMISTACLIENTE,MESFUTURO,ANOFUTURO,CENARIOTIMISTAFATURAMENTO,
							 CENARIOPESSIMISTAFATURAMENTO,CENARIOPROVAVELFAT,CENARIOPROVAVELCLI
							 FROM (
								SELECT
									C.ID_TIPO_CLASSE AS IDCLASSE,C.DESC_CLASSE AS NOMECLASSE,EXTRACT(MONTH FROM B.DT_REALIZADA) AS MES,EXTRACT(YEAR FROM B.DT_REALIZADA) AS ANO,
									SUM(B.QUANTCLIENTE) AS QTDTOTCLIENTEMES,
									(SELECT SUM (C.QUANTCLIENTE) FROM CARGA_DADOS C INNER JOIN ITEM D ON C.ITEM_IDITEM = D.ID_ITEM WHERE D.CLASSE_IDTIPO = C.ID_TIPO_CLASSE
									AND C.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-VALORPARAMETRO),'MONTH') AS DIA FROM CARGA_DADOS)) AS TOTALCLIENTE,
									TRUNC(((SUM(B.QUANTCLIENTE)/(SELECT SUM (C.QUANTCLIENTE) FROM CARGA_DADOS C INNER JOIN ITEM D ON C.ITEM_IDITEM = D.ID_ITEM 
									WHERE D.CLASSE_IDTIPO = C.ID_TIPO_CLASSE AND C.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-VALORPARAMETRO),'MONTH') AS DIA FROM CARGA_DADOS) GROUP BY D.CLASSE_IDTIPO))*100),2) AS VARIACAOCLI,
									SUM(B.QUANTFATURAMENTO) AS QTDTOTFATURAMENTOMES,
									(SELECT SUM (C.QUANTFATURAMENTO) FROM CARGA_DADOS C INNER JOIN ITEM D ON C.ITEM_IDITEM = D.ID_ITEM WHERE D.CLASSE_IDTIPO = C.ID_TIPO_CLASSE
									AND C.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-VALORPARAMETRO),'MONTH') AS DIA FROM CARGA_DADOS)) AS TOTALFATURAMENTO,
									TRUNC(((SUM(B.QUANTFATURAMENTO)/(SELECT SUM (C.QUANTFATURAMENTO) FROM CARGA_DADOS C INNER JOIN ITEM D ON C.ITEM_IDITEM = D.ID_ITEM 
									WHERE D.CLASSE_IDTIPO = C.ID_TIPO_CLASSE AND C.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-VALORPARAMETRO),'MONTH') AS DIA FROM CARGA_DADOS) GROUP BY D.CLASSE_IDTIPO))*100),2) AS VARIACAOFAT,
									EXTRACT (MONTH FROM (SELECT ADD_MONTHS(MAX(A.DT_REALIZADA),1) FROM CARGA_DADOS A INNER JOIN ITEM D ON A.ITEM_IDITEM = D.ID_ITEM 
									WHERE D.CLASSE_IDTIPO = C.ID_TIPO_CLASSE)) AS MESFUTURO,
									EXTRACT (YEAR FROM (SELECT ADD_MONTHS(MAX(A.DT_REALIZADA),1) FROM CARGA_DADOS A INNER JOIN ITEM D ON A.ITEM_IDITEM = D.ID_ITEM 
									WHERE D.CLASSE_IDTIPO = C.ID_TIPO_CLASSE)) AS ANOFUTURO,	
									(TRUNC(((SELECT MAX(VARIACAO) FROM (SELECT D.CLASSE_IDTIPO AS CLASSE,
									TRUNC(((SUM(A.QUANTCLIENTE)/(SELECT SUM (E.QUANTCLIENTE) FROM CARGA_DADOS E INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
									WHERE D.CLASSE_IDTIPO = F.CLASSE_IDTIPO AND E.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-VALORPARAMETRO),'MONTH') AS DIA FROM CARGA_DADOS)))*100),2) AS VARIACAO
									FROM CARGA_DADOS A INNER JOIN ITEM D ON D.ID_ITEM = A.ITEM_IDITEM
									GROUP BY D.CLASSE_IDTIPO, EXTRACT(MONTH FROM A.DT_REALIZADA),EXTRACT(YEAR FROM A.DT_REALIZADA)) WHERE CLASSE = C.ID_TIPO_CLASSE)
									*	
									(SELECT SUM (G.QUANTCLIENTE) FROM CARGA_DADOS G	INNER JOIN ITEM H ON G.ITEM_IDITEM = H.ID_ITEM
									WHERE EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																				INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																				WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																			 INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																			 WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND H.CLASSE_IDTIPO = C.ID_TIPO_CLASSE)/100),0) 
									+
									(SELECT SUM (G.QUANTCLIENTE) FROM CARGA_DADOS G	INNER JOIN ITEM H ON G.ITEM_IDITEM = H.ID_ITEM
									WHERE EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																				INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																				WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																			 INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																			 WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND H.CLASSE_IDTIPO = C.ID_TIPO_CLASSE)) AS CENARIOTIMISTACLIENTE,	
									(TRUNC(((SELECT MIN(VARIACAO) FROM (SELECT D.CLASSE_IDTIPO AS CLASSE,
									TRUNC(((SUM(A.QUANTCLIENTE)/(SELECT SUM (E.QUANTCLIENTE) FROM CARGA_DADOS E INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
									WHERE D.CLASSE_IDTIPO = F.CLASSE_IDTIPO AND E.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-VALORPARAMETRO),'MONTH') AS DIA FROM CARGA_DADOS)))*100),2) AS VARIACAO
									FROM CARGA_DADOS A INNER JOIN ITEM D ON D.ID_ITEM = A.ITEM_IDITEM
									GROUP BY D.CLASSE_IDTIPO, EXTRACT(MONTH FROM A.DT_REALIZADA),EXTRACT(YEAR FROM A.DT_REALIZADA)) WHERE CLASSE = C.ID_TIPO_CLASSE)
									*	
									(SELECT SUM (G.QUANTCLIENTE) FROM CARGA_DADOS G	INNER JOIN ITEM H ON G.ITEM_IDITEM = H.ID_ITEM
									WHERE EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																				INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																				WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																			 INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																			 WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND H.CLASSE_IDTIPO = C.ID_TIPO_CLASSE)/100),0) 
									+
									(SELECT SUM (G.QUANTCLIENTE) FROM CARGA_DADOS G	INNER JOIN ITEM H ON G.ITEM_IDITEM = H.ID_ITEM
									WHERE EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																				INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																				WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																			 INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																			 WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND H.CLASSE_IDTIPO = C.ID_TIPO_CLASSE)) AS CENARIOPESSIMISTACLIENTE,	
									(TRUNC(((SELECT MAX(VARIACAO) FROM (SELECT D.CLASSE_IDTIPO AS CLASSE,
									TRUNC(((SUM(A.QUANTFATURAMENTO)/(SELECT SUM (E.QUANTFATURAMENTO) FROM CARGA_DADOS E INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
									WHERE D.CLASSE_IDTIPO = F.CLASSE_IDTIPO AND E.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-VALORPARAMETRO),'MONTH') AS DIA FROM CARGA_DADOS)))*100),2) AS VARIACAO
									FROM CARGA_DADOS A INNER JOIN ITEM D ON D.ID_ITEM = A.ITEM_IDITEM
									GROUP BY D.CLASSE_IDTIPO, EXTRACT(MONTH FROM A.DT_REALIZADA),EXTRACT(YEAR FROM A.DT_REALIZADA)) WHERE CLASSE = C.ID_TIPO_CLASSE)
									*	
									(SELECT SUM (G.QUANTFATURAMENTO) FROM CARGA_DADOS G	INNER JOIN ITEM H ON G.ITEM_IDITEM = H.ID_ITEM
									WHERE EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																				INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																				WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																			 INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																			 WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND H.CLASSE_IDTIPO = C.ID_TIPO_CLASSE)/100),0) 
									+
									(SELECT SUM (G.QUANTFATURAMENTO) FROM CARGA_DADOS G	INNER JOIN ITEM H ON G.ITEM_IDITEM = H.ID_ITEM
									WHERE EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																				INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																				WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																			 INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																			 WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND H.CLASSE_IDTIPO = C.ID_TIPO_CLASSE)) AS CENARIOTIMISTAFATURAMENTO,	
									(TRUNC(((SELECT MIN(VARIACAO) FROM (SELECT D.CLASSE_IDTIPO AS CLASSE,
									TRUNC(((SUM(A.QUANTFATURAMENTO)/(SELECT SUM (E.QUANTFATURAMENTO) FROM CARGA_DADOS E INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
									WHERE D.CLASSE_IDTIPO = F.CLASSE_IDTIPO AND E.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-VALORPARAMETRO),'MONTH') AS DIA FROM CARGA_DADOS)))*100),2) AS VARIACAO
									FROM CARGA_DADOS A INNER JOIN ITEM D ON D.ID_ITEM = A.ITEM_IDITEM
									GROUP BY D.CLASSE_IDTIPO, EXTRACT(MONTH FROM A.DT_REALIZADA),EXTRACT(YEAR FROM A.DT_REALIZADA)) WHERE CLASSE = C.ID_TIPO_CLASSE)
									*	
									(SELECT SUM (G.QUANTFATURAMENTO) FROM CARGA_DADOS G	INNER JOIN ITEM H ON G.ITEM_IDITEM = H.ID_ITEM
									WHERE EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																				INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																				WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																			 INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																			 WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND H.CLASSE_IDTIPO = C.ID_TIPO_CLASSE)/100),0) 
									+
									(SELECT SUM (G.QUANTFATURAMENTO) FROM CARGA_DADOS G	INNER JOIN ITEM H ON G.ITEM_IDITEM = H.ID_ITEM
									WHERE EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																				INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																				WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																			 INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																			 WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND H.CLASSE_IDTIPO = C.ID_TIPO_CLASSE)) AS CENARIOPESSIMISTAFATURAMENTO,
									TRUNC((TRUNC
								   (((SELECT TRUNC(((SUM (D.QUANTFATURAMENTO)/(SELECT SUM (B.QUANTFATURAMENTO) FROM CARGA_DADOS B INNER JOIN ITEM H ON B.ITEM_IDITEM = H.ID_ITEM
									  WHERE H.CLASSE_IDTIPO = E.CLASSE_IDTIPO AND B.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-6),'MONTH') AS DIA FROM CARGA_DADOS)))*100),2)  
									  FROM CARGA_DADOS D 
									  INNER JOIN ITEM E ON D.ITEM_IDITEM = E.ID_ITEM
									  WHERE E.CLASSE_IDTIPO = C.ID_TIPO_CLASSE								      
								      AND EXTRACT (YEAR FROM D.DT_REALIZADA) = (SELECT MAX (ANO) FROM (SELECT EXTRACT (YEAR FROM C.DT_REALIZADA) AS ANO FROM CARGA_DADOS C))
									  AND EXTRACT (MONTH FROM D.DT_REALIZADA) = (SELECT MAX (MES) FROM (SELECT EXTRACT (MONTH FROM C.DT_REALIZADA) AS MES FROM CARGA_DADOS C
																				WHERE EXTRACT (YEAR FROM C.DT_REALIZADA) = 
																				(SELECT MAX (ANO) FROM (SELECT EXTRACT (YEAR FROM C.DT_REALIZADA) AS ANO FROM CARGA_DADOS C))))
									  GROUP BY E.CLASSE_IDTIPO, EXTRACT(MONTH FROM D.DT_REALIZADA),EXTRACT(YEAR FROM D.DT_REALIZADA))
									  *
									  (SELECT SUM (G.QUANTFATURAMENTO) FROM CARGA_DADOS G	INNER JOIN ITEM H ON G.ITEM_IDITEM = H.ID_ITEM
									  WHERE EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																				 INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																				 WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									  AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																			   INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																			   WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)									  									  
									  AND H.CLASSE_IDTIPO = C.ID_TIPO_CLASSE)/100),0)
									  +
									  (SELECT SUM (G.QUANTFATURAMENTO) FROM CARGA_DADOS G INNER JOIN ITEM H ON G.ITEM_IDITEM = H.ID_ITEM
									  WHERE EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																			 	 INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																				 WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									  AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																			   INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																			   WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)								 	  
									  AND H.CLASSE_IDTIPO = C.ID_TIPO_CLASSE)),0) AS CENARIOPROVAVELFAT,
									  TRUNC((TRUNC
										(((SELECT TRUNC(((SUM (D.QUANTCLIENTE)/(SELECT SUM (B.QUANTCLIENTE) FROM CARGA_DADOS B INNER JOIN ITEM H ON B.ITEM_IDITEM = H.ID_ITEM
										WHERE H.CLASSE_IDTIPO = E.CLASSE_IDTIPO AND B.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-6),'MONTH') AS DIA FROM CARGA_DADOS)))*100),2)  
										FROM CARGA_DADOS D 
										INNER JOIN ITEM E ON D.ITEM_IDITEM = E.ID_ITEM
										WHERE E.CLASSE_IDTIPO = C.ID_TIPO_CLASSE										
										AND EXTRACT (YEAR FROM D.DT_REALIZADA) = (SELECT MAX (ANO) FROM (SELECT EXTRACT (YEAR FROM C.DT_REALIZADA) AS ANO FROM CARGA_DADOS C))
										AND EXTRACT (MONTH FROM D.DT_REALIZADA) = (SELECT MAX (MES) FROM (SELECT EXTRACT (MONTH FROM C.DT_REALIZADA) AS MES FROM CARGA_DADOS C
																				   WHERE EXTRACT (YEAR FROM C.DT_REALIZADA) = 
																				   (SELECT MAX (ANO) FROM (SELECT EXTRACT (YEAR FROM C.DT_REALIZADA) AS ANO FROM CARGA_DADOS C))))
										GROUP BY E.CLASSE_IDTIPO, EXTRACT(MONTH FROM D.DT_REALIZADA),EXTRACT(YEAR FROM D.DT_REALIZADA))
										*
										(SELECT SUM (G.QUANTCLIENTE) FROM CARGA_DADOS G	INNER JOIN ITEM H ON G.ITEM_IDITEM = H.ID_ITEM
										 WHERE EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																					 INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																					 WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
										 AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																				  INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																				  WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)																				  
										 AND H.CLASSE_IDTIPO = C.ID_TIPO_CLASSE)/100),0)
										  +
										 (SELECT SUM (G.QUANTCLIENTE) FROM CARGA_DADOS G INNER JOIN ITEM H ON G.ITEM_IDITEM = H.ID_ITEM
										 WHERE EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																					 INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																					 WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
										 AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																				  INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																				   WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)										 
										 AND H.CLASSE_IDTIPO = C.ID_TIPO_CLASSE)),0) AS CENARIOPROVAVELCLI	
									
								FROM ITEM A 
								INNER JOIN CARGA_DADOS B ON A.ID_ITEM = B.ITEM_IDITEM
								INNER JOIN TIPOCLASSE C ON A.CLASSE_IDTIPO = C.ID_TIPO_CLASSE
								WHERE B.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-VALORPARAMETRO),'MONTH') AS DIA FROM CARGA_DADOS)
								GROUP BY C.ID_TIPO_CLASSE,C.DESC_CLASSE,EXTRACT(MONTH FROM B.DT_REALIZADA),EXTRACT(YEAR FROM B.DT_REALIZADA)
								ORDER BY 2,4,3)
								WHERE VARIACAOCLI = (SELECT MAX(VARIACAO) FROM (SELECT D.CLASSE_IDTIPO AS CLASSE,
								TRUNC(((SUM(A.QUANTCLIENTE)/(SELECT SUM (E.QUANTCLIENTE) FROM CARGA_DADOS E INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
								WHERE D.CLASSE_IDTIPO = F.CLASSE_IDTIPO AND E.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-VALORPARAMETRO),'MONTH') AS DIA FROM CARGA_DADOS)))*100),2) AS VARIACAO
								FROM CARGA_DADOS A INNER JOIN ITEM D ON D.ID_ITEM = A.ITEM_IDITEM
								GROUP BY D.CLASSE_IDTIPO, EXTRACT(MONTH FROM A.DT_REALIZADA),EXTRACT(YEAR FROM A.DT_REALIZADA)) WHERE CLASSE = IDCLASSE));
								
								
				
			CURSOR LISTA02 IS (SELECT IDCLASSE,NOMECLASSE,QTDTOTCLIENTEMES,TOTALCLIENTE,VARIACAOCLI,TOTALFATURAMENTO,VARIACAOFAT,
							   MES,ANO,CENARIOTIMISTACLIENTE,CENARIOPESSIMISTACLIENTE,MESFUTURO,ANOFUTURO,CENARIOTIMISTAFATURAMENTO,
							   CENARIOPESSIMISTAFATURAMENTO,CENARIOPROVAVELFAT,CENARIOPROVAVELCLI
							   FROM (SELECT
									C.ID_TIPO_CLASSE AS IDCLASSE,C.DESC_CLASSE AS NOMECLASSE,EXTRACT(MONTH FROM B.DT_REALIZADA) AS MES,EXTRACT(YEAR FROM B.DT_REALIZADA) AS ANO,
									SUM(B.QUANTCLIENTE) AS QTDTOTCLIENTEMES,
									(SELECT SUM (C.QUANTCLIENTE) FROM CARGA_DADOS C INNER JOIN ITEM D ON C.ITEM_IDITEM = D.ID_ITEM WHERE D.CLASSE_IDTIPO = C.ID_TIPO_CLASSE
									AND EXTRACT(DAY FROM C.DT_REALIZADA) BETWEEN 1 AND 15 
									AND C.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-6),'MONTH') AS DIA FROM CARGA_DADOS)) AS TOTALCLIENTE,
									TRUNC(((SUM(B.QUANTCLIENTE)/(SELECT SUM (C.QUANTCLIENTE) FROM CARGA_DADOS C INNER JOIN ITEM D ON C.ITEM_IDITEM = D.ID_ITEM 
									WHERE D.CLASSE_IDTIPO = C.ID_TIPO_CLASSE 
									AND EXTRACT(DAY FROM C.DT_REALIZADA) BETWEEN 1 AND 15 
									AND C.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-6),'MONTH') AS DIA FROM CARGA_DADOS) GROUP BY D.CLASSE_IDTIPO))*100),2) AS VARIACAOCLI,
									SUM(B.QUANTFATURAMENTO) AS QTDTOTFATURAMENTOMES,
									(SELECT SUM (C.QUANTFATURAMENTO) FROM CARGA_DADOS C INNER JOIN ITEM D ON C.ITEM_IDITEM = D.ID_ITEM WHERE D.CLASSE_IDTIPO = C.ID_TIPO_CLASSE
									AND EXTRACT(DAY FROM C.DT_REALIZADA) BETWEEN 1 AND 15 
									AND C.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-6),'MONTH') AS DIA FROM CARGA_DADOS)) AS TOTALFATURAMENTO,
									TRUNC(((SUM(B.QUANTFATURAMENTO)/(SELECT SUM (C.QUANTFATURAMENTO) FROM CARGA_DADOS C INNER JOIN ITEM D ON C.ITEM_IDITEM = D.ID_ITEM 
									WHERE D.CLASSE_IDTIPO = C.ID_TIPO_CLASSE 
									AND EXTRACT(DAY FROM C.DT_REALIZADA) BETWEEN 1 AND 15 
									AND C.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-6),'MONTH') AS DIA FROM CARGA_DADOS) GROUP BY D.CLASSE_IDTIPO))*100),2) AS VARIACAOFAT,
									EXTRACT (MONTH FROM (SELECT ADD_MONTHS(MAX(A.DT_REALIZADA),1) FROM CARGA_DADOS A INNER JOIN ITEM D ON A.ITEM_IDITEM = D.ID_ITEM 
									WHERE D.CLASSE_IDTIPO = C.ID_TIPO_CLASSE)) AS MESFUTURO,
									EXTRACT (YEAR FROM (SELECT ADD_MONTHS(MAX(A.DT_REALIZADA),1) FROM CARGA_DADOS A INNER JOIN ITEM D ON A.ITEM_IDITEM = D.ID_ITEM 
									WHERE D.CLASSE_IDTIPO = C.ID_TIPO_CLASSE)) AS ANOFUTURO,	
									(TRUNC(((SELECT MAX(VARIACAO) FROM (SELECT D.CLASSE_IDTIPO AS CLASSE,
									TRUNC(((SUM(A.QUANTCLIENTE)/(SELECT SUM (E.QUANTCLIENTE) FROM CARGA_DADOS E INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
									WHERE D.CLASSE_IDTIPO = F.CLASSE_IDTIPO 
									AND EXTRACT(DAY FROM E.DT_REALIZADA) BETWEEN 1 AND 15 
									AND E.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-6),'MONTH') AS DIA FROM CARGA_DADOS)))*100),2) AS VARIACAO
									FROM CARGA_DADOS A INNER JOIN ITEM D ON D.ID_ITEM = A.ITEM_IDITEM
									WHERE EXTRACT(DAY FROM A.DT_REALIZADA) BETWEEN 1 AND 15 	
									GROUP BY D.CLASSE_IDTIPO, EXTRACT(MONTH FROM A.DT_REALIZADA),EXTRACT(YEAR FROM A.DT_REALIZADA)) WHERE CLASSE = C.ID_TIPO_CLASSE)
									*	
									(SELECT SUM (G.QUANTCLIENTE) FROM CARGA_DADOS G	INNER JOIN ITEM H ON G.ITEM_IDITEM = H.ID_ITEM
									WHERE EXTRACT(DAY FROM G.DT_REALIZADA) BETWEEN 1 AND 15									
									AND EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																				INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																				WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																			 INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																			 WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND H.CLASSE_IDTIPO = C.ID_TIPO_CLASSE)/100),0) 
									+
									(SELECT SUM (G.QUANTCLIENTE) FROM CARGA_DADOS G	INNER JOIN ITEM H ON G.ITEM_IDITEM = H.ID_ITEM
									WHERE EXTRACT(DAY FROM G.DT_REALIZADA) BETWEEN 1 AND 15 									
									AND EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																				INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																				WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																			 INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																			 WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND H.CLASSE_IDTIPO = C.ID_TIPO_CLASSE)) AS CENARIOTIMISTACLIENTE,	
									(TRUNC(((SELECT MIN(VARIACAO) FROM (SELECT D.CLASSE_IDTIPO AS CLASSE,
									TRUNC(((SUM(A.QUANTCLIENTE)/(SELECT SUM (E.QUANTCLIENTE) FROM CARGA_DADOS E INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
									WHERE D.CLASSE_IDTIPO = F.CLASSE_IDTIPO 
									AND EXTRACT(DAY FROM E.DT_REALIZADA) BETWEEN 1 AND 15 	
									AND E.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-6),'MONTH') AS DIA FROM CARGA_DADOS)))*100),2) AS VARIACAO
									FROM CARGA_DADOS A INNER JOIN ITEM D ON D.ID_ITEM = A.ITEM_IDITEM
									WHERE EXTRACT(DAY FROM A.DT_REALIZADA) BETWEEN 1 AND 15 	
									GROUP BY D.CLASSE_IDTIPO, EXTRACT(MONTH FROM A.DT_REALIZADA),EXTRACT(YEAR FROM A.DT_REALIZADA)) WHERE CLASSE = C.ID_TIPO_CLASSE)
									*	
									(SELECT SUM (G.QUANTCLIENTE) FROM CARGA_DADOS G	INNER JOIN ITEM H ON G.ITEM_IDITEM = H.ID_ITEM
									WHERE EXTRACT(DAY FROM G.DT_REALIZADA) BETWEEN 1 AND 15 	
									AND EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																				INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																				WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																			 INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																			 WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND H.CLASSE_IDTIPO = C.ID_TIPO_CLASSE)/100),0) 
									+
									(SELECT SUM (G.QUANTCLIENTE) FROM CARGA_DADOS G	INNER JOIN ITEM H ON G.ITEM_IDITEM = H.ID_ITEM
									WHERE EXTRACT(DAY FROM G.DT_REALIZADA) BETWEEN 1 AND 15 	
									AND EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																				INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																				WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																			 INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																			 WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND H.CLASSE_IDTIPO = C.ID_TIPO_CLASSE)) AS CENARIOPESSIMISTACLIENTE,	
									(TRUNC(((SELECT MAX(VARIACAO) FROM (SELECT D.CLASSE_IDTIPO AS CLASSE,
									TRUNC(((SUM(A.QUANTFATURAMENTO)/(SELECT SUM (E.QUANTFATURAMENTO) FROM CARGA_DADOS E INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
									WHERE D.CLASSE_IDTIPO = F.CLASSE_IDTIPO
									AND EXTRACT(DAY FROM E.DT_REALIZADA) BETWEEN 1 AND 15 	
									AND E.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-6),'MONTH') AS DIA FROM CARGA_DADOS)))*100),2) AS VARIACAO
									FROM CARGA_DADOS A INNER JOIN ITEM D ON D.ID_ITEM = A.ITEM_IDITEM
									WHERE EXTRACT(DAY FROM A.DT_REALIZADA) BETWEEN 1 AND 15 	
									GROUP BY D.CLASSE_IDTIPO, EXTRACT(MONTH FROM A.DT_REALIZADA),EXTRACT(YEAR FROM A.DT_REALIZADA)) WHERE CLASSE = C.ID_TIPO_CLASSE)
									*	
									(SELECT SUM (G.QUANTFATURAMENTO) FROM CARGA_DADOS G	INNER JOIN ITEM H ON G.ITEM_IDITEM = H.ID_ITEM
									WHERE EXTRACT(DAY FROM G.DT_REALIZADA) BETWEEN 1 AND 15 	
									AND EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																				INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																				WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																			 INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																			 WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND H.CLASSE_IDTIPO = C.ID_TIPO_CLASSE)/100),0) 
									+
									(SELECT SUM (G.QUANTFATURAMENTO) FROM CARGA_DADOS G	INNER JOIN ITEM H ON G.ITEM_IDITEM = H.ID_ITEM
									WHERE EXTRACT(DAY FROM G.DT_REALIZADA) BETWEEN 1 AND 15 	
									AND EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																				INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																				WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																			 INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																			 WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND H.CLASSE_IDTIPO = C.ID_TIPO_CLASSE)) AS CENARIOTIMISTAFATURAMENTO,	
									(TRUNC(((SELECT MIN(VARIACAO) FROM (SELECT D.CLASSE_IDTIPO AS CLASSE,
									TRUNC(((SUM(A.QUANTFATURAMENTO)/(SELECT SUM (E.QUANTFATURAMENTO) FROM CARGA_DADOS E INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
									WHERE D.CLASSE_IDTIPO = F.CLASSE_IDTIPO
                                    AND EXTRACT(DAY FROM E.DT_REALIZADA) BETWEEN 1 AND 15 	
									AND E.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-6),'MONTH') AS DIA FROM CARGA_DADOS)))*100),2) AS VARIACAO
									FROM CARGA_DADOS A INNER JOIN ITEM D ON D.ID_ITEM = A.ITEM_IDITEM
									WHERE EXTRACT(DAY FROM A.DT_REALIZADA) BETWEEN 1 AND 15 	
									GROUP BY D.CLASSE_IDTIPO, EXTRACT(MONTH FROM A.DT_REALIZADA),EXTRACT(YEAR FROM A.DT_REALIZADA)) WHERE CLASSE = C.ID_TIPO_CLASSE)
									*	
									(SELECT SUM (G.QUANTFATURAMENTO) FROM CARGA_DADOS G	INNER JOIN ITEM H ON G.ITEM_IDITEM = H.ID_ITEM
									WHERE EXTRACT(DAY FROM G.DT_REALIZADA) BETWEEN 1 AND 15 	
									AND EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																				INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																				WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																			 INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																			 WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND H.CLASSE_IDTIPO = C.ID_TIPO_CLASSE)/100),0) 
									+
									(SELECT SUM (G.QUANTFATURAMENTO) FROM CARGA_DADOS G	INNER JOIN ITEM H ON G.ITEM_IDITEM = H.ID_ITEM
									WHERE EXTRACT(DAY FROM G.DT_REALIZADA) BETWEEN 1 AND 15 	
									AND EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																				INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																				WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																			 INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																			 WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND H.CLASSE_IDTIPO = C.ID_TIPO_CLASSE)) AS CENARIOPESSIMISTAFATURAMENTO,
								   TRUNC((TRUNC
								   (((SELECT TRUNC(((SUM (D.QUANTFATURAMENTO)/(SELECT SUM (B.QUANTFATURAMENTO) FROM CARGA_DADOS B INNER JOIN ITEM H ON B.ITEM_IDITEM = H.ID_ITEM
									  WHERE H.CLASSE_IDTIPO = E.CLASSE_IDTIPO AND B.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-6),'MONTH') AS DIA FROM CARGA_DADOS)
									  AND EXTRACT(DAY FROM B.DT_REALIZADA) BETWEEN 1 AND 15))*100),2)  
									  FROM CARGA_DADOS D 
									  INNER JOIN ITEM E ON D.ITEM_IDITEM = E.ID_ITEM
									  WHERE E.CLASSE_IDTIPO = C.ID_TIPO_CLASSE
								      AND EXTRACT(DAY FROM D.DT_REALIZADA) BETWEEN 1 AND 15 
								      AND EXTRACT (YEAR FROM D.DT_REALIZADA) = (SELECT MAX (ANO) FROM (SELECT EXTRACT (YEAR FROM C.DT_REALIZADA) AS ANO FROM CARGA_DADOS C))
									  AND EXTRACT (MONTH FROM D.DT_REALIZADA) = (SELECT MAX (MES) FROM (SELECT EXTRACT (MONTH FROM C.DT_REALIZADA) AS MES FROM CARGA_DADOS C
																				WHERE EXTRACT (YEAR FROM C.DT_REALIZADA) = 
																				(SELECT MAX (ANO) FROM (SELECT EXTRACT (YEAR FROM C.DT_REALIZADA) AS ANO FROM CARGA_DADOS C))))
									  GROUP BY E.CLASSE_IDTIPO, EXTRACT(MONTH FROM D.DT_REALIZADA),EXTRACT(YEAR FROM D.DT_REALIZADA))
									  *
									  (SELECT SUM (G.QUANTFATURAMENTO) FROM CARGA_DADOS G	INNER JOIN ITEM H ON G.ITEM_IDITEM = H.ID_ITEM
									  WHERE EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																				 INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																				 WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									  AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																			   INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																			   WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									  AND EXTRACT(DAY FROM G.DT_REALIZADA) BETWEEN 1 AND 15										  
									  AND H.CLASSE_IDTIPO = C.ID_TIPO_CLASSE)/100),0)
									  +
									  (SELECT SUM (G.QUANTFATURAMENTO) FROM CARGA_DADOS G INNER JOIN ITEM H ON G.ITEM_IDITEM = H.ID_ITEM
									  WHERE EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																			 	 INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																				 WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									  AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																			   INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																			   WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
								 	  AND EXTRACT(DAY FROM G.DT_REALIZADA) BETWEEN 1 AND 15
									  AND H.CLASSE_IDTIPO = C.ID_TIPO_CLASSE)),0) AS CENARIOPROVAVELFAT,
									  TRUNC((TRUNC
										(((SELECT TRUNC(((SUM (D.QUANTCLIENTE)/(SELECT SUM (B.QUANTCLIENTE) FROM CARGA_DADOS B INNER JOIN ITEM H ON B.ITEM_IDITEM = H.ID_ITEM
										WHERE H.CLASSE_IDTIPO = E.CLASSE_IDTIPO AND B.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-6),'MONTH') AS DIA FROM CARGA_DADOS)
										AND EXTRACT(DAY FROM B.DT_REALIZADA) BETWEEN 1 AND 15))*100),2)  
										FROM CARGA_DADOS D 
										INNER JOIN ITEM E ON D.ITEM_IDITEM = E.ID_ITEM
										WHERE E.CLASSE_IDTIPO = C.ID_TIPO_CLASSE
										AND EXTRACT(DAY FROM D.DT_REALIZADA) BETWEEN 1 AND 15 
										AND EXTRACT (YEAR FROM D.DT_REALIZADA) = (SELECT MAX (ANO) FROM (SELECT EXTRACT (YEAR FROM C.DT_REALIZADA) AS ANO FROM CARGA_DADOS C))
										AND EXTRACT (MONTH FROM D.DT_REALIZADA) = (SELECT MAX (MES) FROM (SELECT EXTRACT (MONTH FROM C.DT_REALIZADA) AS MES FROM CARGA_DADOS C
																				   WHERE EXTRACT (YEAR FROM C.DT_REALIZADA) = 
																				   (SELECT MAX (ANO) FROM (SELECT EXTRACT (YEAR FROM C.DT_REALIZADA) AS ANO FROM CARGA_DADOS C))))
										GROUP BY E.CLASSE_IDTIPO, EXTRACT(MONTH FROM D.DT_REALIZADA),EXTRACT(YEAR FROM D.DT_REALIZADA))
										*
										(SELECT SUM (G.QUANTCLIENTE) FROM CARGA_DADOS G	INNER JOIN ITEM H ON G.ITEM_IDITEM = H.ID_ITEM
										 WHERE EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																					 INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																					 WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
										 AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																				  INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																				  WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
										 AND EXTRACT(DAY FROM G.DT_REALIZADA) BETWEEN 1 AND 15										  
										 AND H.CLASSE_IDTIPO = C.ID_TIPO_CLASSE)/100),0)
										  +
										 (SELECT SUM (G.QUANTCLIENTE) FROM CARGA_DADOS G INNER JOIN ITEM H ON G.ITEM_IDITEM = H.ID_ITEM
										 WHERE EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																					 INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																					 WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
										 AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																				  INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																				   WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
										 AND EXTRACT(DAY FROM G.DT_REALIZADA) BETWEEN 1 AND 15
										 AND H.CLASSE_IDTIPO = C.ID_TIPO_CLASSE)),0) AS CENARIOPROVAVELCLI											
									
								FROM ITEM A 
								INNER JOIN CARGA_DADOS B ON A.ID_ITEM = B.ITEM_IDITEM
								INNER JOIN TIPOCLASSE C ON A.CLASSE_IDTIPO = C.ID_TIPO_CLASSE
								WHERE B.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-6),'MONTH') AS DIA FROM CARGA_DADOS)
								AND EXTRACT(DAY FROM B.DT_REALIZADA) BETWEEN 1 AND 15 
								GROUP BY C.ID_TIPO_CLASSE,C.DESC_CLASSE,EXTRACT(MONTH FROM B.DT_REALIZADA),EXTRACT(YEAR FROM B.DT_REALIZADA)
								ORDER BY 2,4,3)
								
								WHERE VARIACAOCLI = (SELECT MAX(VARIACAO) FROM (SELECT D.CLASSE_IDTIPO AS CLASSE,
								TRUNC(((SUM(A.QUANTCLIENTE)/(SELECT SUM (E.QUANTCLIENTE) FROM CARGA_DADOS E INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
								WHERE D.CLASSE_IDTIPO = F.CLASSE_IDTIPO 
								AND EXTRACT(DAY FROM E.DT_REALIZADA) BETWEEN 1 AND 15 
								AND E.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-VALORPARAMETRO),'MONTH') AS DIA FROM CARGA_DADOS)))*100),2) AS VARIACAO
								FROM CARGA_DADOS A INNER JOIN ITEM D ON D.ID_ITEM = A.ITEM_IDITEM
								WHERE EXTRACT(DAY FROM A.DT_REALIZADA) BETWEEN 1 AND 15 
								GROUP BY D.CLASSE_IDTIPO, EXTRACT(MONTH FROM A.DT_REALIZADA),EXTRACT(YEAR FROM A.DT_REALIZADA)) WHERE CLASSE = IDCLASSE));						
								
								
			BEGIN
                SELECT COUNT(*) INTO TOTALCONT FROM (SELECT B.CLASSE_IDTIPO FROM CARGA_DADOS A 
													 INNER JOIN ITEM B ON A.ITEM_IDITEM = B.ID_ITEM
													 GROUP BY B.CLASSE_IDTIPO);
				SELECT COALESCE(MES,0) INTO MESINSERIDO FROM (SELECT MAX(MESFUTURO) AS MES FROM DADOS_FUTUROS_GRUPO);
				SELECT COALESCE(ANO,0) INTO ANOINSERIDO FROM (SELECT MAX(ANOFUTURO) AS ANO FROM DADOS_FUTUROS_GRUPO);				
				DBMS_OUTPUT.ENABLE (100000000);				
				OPEN LISTA;				
				FETCH LISTA INTO IDITEM,NOMEITEM,QTDTOTCLIENTEMES,TOTALCLIENTE,VARIACAOCLI,TOTALFATURAMENTO,VARIACAOFAT,
				MESVARIADO,ANOVARIADO,CENARIOTIMISTACLIENTE,CENARIOPESSIMISTACLIENTE,MESFUTURO,ANOFUTURO,CENARIOTIMISTAFATURAMENTO,
				CENARIOPESSIMISTAFATURAMENTO,CENARIOPROVAVELFAT,CENARIOPROVAVELCLI;
				OPEN LISTA02;				
				FETCH LISTA02 INTO IDITEM01,NOMEITEM01,QTDTOTCLIENTEMES01,TOTALCLIENTE01,VARIACAOCLI01,TOTALFATURAMENTO01,VARIACAOFAT01,
				MESVARIADO01,ANOVARIADO01,CENARIOTIMISTACLIENTE01,CENARIOPESSIMISTACLIENTE01,MESFUTURO01,ANOFUTURO01,CENARIOTIMISTAFATURAMENTO01,
				CENARIOPESSIMISTAFATURAMENTO01,CENARIOPROVAVELFAT01,CENARIOPROVAVELCLI01;
				WHILE CONTADOR < TOTALCONT
					LOOP 			
						 IF (MESFUTURO <> MESINSERIDO AND ANOFUTURO <> ANOINSERIDO) THEN
								CONTADOR := CONTADOR + 1;
								INSERT INTO DADOS_FUTUROS_GRUPO (ID_DADOS_FUTUROS_GRUPO,ID_GRUPO,NOME_GRUPO,QTDTOTCLIENTEMES,TOTALCLIENTE,
								VARIACAOCLI,TOTALFATURAMENTO,VARIACAOFAT,MESVARIADO,ANOVARIADO,CENARIOTIMISTACLIENTE,CENARIOPESSIMISTACLIENTE,
								MESFUTURO,ANOFUTURO,CENARIOTIMISTAFATURAMENTO,CENARIOPESSIMISTAFATURAMENTO,CENARIOPROVAVELFAT,CENARIOPROVAVELCLI,
								TIPO_PROCESSAMENTO,DATAPROCESSAMENTO,ITEM_REPROCESSADO)
								VALUES (IDDADOSFUTUROSGRUPO.NEXTVAL,IDITEM,NOMEITEM,QTDTOTCLIENTEMES,TOTALCLIENTE,VARIACAOCLI,TOTALFATURAMENTO,
								VARIACAOFAT,MESVARIADO,ANOVARIADO,CENARIOTIMISTACLIENTE,CENARIOPESSIMISTACLIENTE,MESFUTURO,ANOFUTURO,CENARIOTIMISTAFATURAMENTO,
								CENARIOPESSIMISTAFATURAMENTO,CENARIOPROVAVELFAT,CENARIOPROVAVELCLI,2,(SELECT TO_CHAR (SYSDATE,'DD/MM/YYYY HH24:MM:SS') FROM DUAL),'N');						
								FETCH LISTA INTO IDITEM,NOMEITEM,QTDTOTCLIENTEMES,TOTALCLIENTE,VARIACAOCLI,TOTALFATURAMENTO,VARIACAOFAT,
								MESVARIADO,ANOVARIADO,CENARIOTIMISTACLIENTE,CENARIOPESSIMISTACLIENTE,MESFUTURO,ANOFUTURO,CENARIOTIMISTAFATURAMENTO,
								CENARIOPESSIMISTAFATURAMENTO,CENARIOPROVAVELFAT,CENARIOPROVAVELCLI;
								
								INSERT INTO DADOS_FUTUROS_GRUPO (ID_DADOS_FUTUROS_GRUPO,ID_GRUPO,NOME_GRUPO,QTDTOTCLIENTEMES,TOTALCLIENTE,
								VARIACAOCLI,TOTALFATURAMENTO,VARIACAOFAT,MESVARIADO,ANOVARIADO,CENARIOTIMISTACLIENTE,CENARIOPESSIMISTACLIENTE,
								MESFUTURO,ANOFUTURO,CENARIOTIMISTAFATURAMENTO,CENARIOPESSIMISTAFATURAMENTO,CENARIOPROVAVELFAT,CENARIOPROVAVELCLI,
								TIPO_PROCESSAMENTO,DATAPROCESSAMENTO,ITEM_REPROCESSADO)
								VALUES (IDDADOSFUTUROSGRUPO.NEXTVAL,IDITEM01,NOMEITEM01,QTDTOTCLIENTEMES01,TOTALCLIENTE01,VARIACAOCLI01,TOTALFATURAMENTO01,
								VARIACAOFAT01,MESVARIADO01,ANOVARIADO01,CENARIOTIMISTACLIENTE01,CENARIOPESSIMISTACLIENTE01,MESFUTURO01,ANOFUTURO01,CENARIOTIMISTAFATURAMENTO01,
								CENARIOPESSIMISTAFATURAMENTO01,CENARIOPROVAVELFAT01,CENARIOPROVAVELCLI01,1,(SELECT TO_CHAR (SYSDATE,'DD/MM/YYYY HH24:MM:SS') FROM DUAL),'N');						
								FETCH LISTA02 INTO IDITEM01,NOMEITEM01,QTDTOTCLIENTEMES01,TOTALCLIENTE01,VARIACAOCLI01,TOTALFATURAMENTO01,VARIACAOFAT01,
								MESVARIADO01,ANOVARIADO01,CENARIOTIMISTACLIENTE01,CENARIOPESSIMISTACLIENTE01,MESFUTURO01,ANOFUTURO01,CENARIOTIMISTAFATURAMENTO01,
								CENARIOPESSIMISTAFATURAMENTO01,CENARIOPROVAVELFAT01,CENARIOPROVAVELCLI01;								
						 ELSE
								CONTADOR := CONTADOR + 1;
								INSERT INTO DADOS_FUTUROS_GRUPO (ID_DADOS_FUTUROS_GRUPO,ID_GRUPO,NOME_GRUPO,QTDTOTCLIENTEMES,TOTALCLIENTE,
								VARIACAOCLI,TOTALFATURAMENTO,VARIACAOFAT,MESVARIADO,ANOVARIADO,CENARIOTIMISTACLIENTE,CENARIOPESSIMISTACLIENTE,
								MESFUTURO,ANOFUTURO,CENARIOTIMISTAFATURAMENTO,CENARIOPESSIMISTAFATURAMENTO,CENARIOPROVAVELFAT,CENARIOPROVAVELCLI,
								TIPO_PROCESSAMENTO,DATAPROCESSAMENTO,ITEM_REPROCESSADO)
								VALUES (IDDADOSFUTUROSGRUPO.NEXTVAL,IDITEM,NOMEITEM,QTDTOTCLIENTEMES,TOTALCLIENTE,VARIACAOCLI,TOTALFATURAMENTO,
								VARIACAOFAT,MESVARIADO,ANOVARIADO,CENARIOTIMISTACLIENTE,CENARIOPESSIMISTACLIENTE,MESFUTURO,ANOFUTURO,CENARIOTIMISTAFATURAMENTO,
								CENARIOPESSIMISTAFATURAMENTO,CENARIOPROVAVELFAT,CENARIOPROVAVELCLI,2,(SELECT TO_CHAR (SYSDATE,'DD/MM/YYYY HH24:MM:SS') FROM DUAL),'S');						
								FETCH LISTA INTO IDITEM,NOMEITEM,QTDTOTCLIENTEMES,TOTALCLIENTE,VARIACAOCLI,TOTALFATURAMENTO,VARIACAOFAT,
								MESVARIADO,ANOVARIADO,CENARIOTIMISTACLIENTE,CENARIOPESSIMISTACLIENTE,MESFUTURO,ANOFUTURO,CENARIOTIMISTAFATURAMENTO,
								CENARIOPESSIMISTAFATURAMENTO,CENARIOPROVAVELFAT,CENARIOPROVAVELCLI;
								
								INSERT INTO DADOS_FUTUROS_GRUPO (ID_DADOS_FUTUROS_GRUPO,ID_GRUPO,NOME_GRUPO,QTDTOTCLIENTEMES,TOTALCLIENTE,
								VARIACAOCLI,TOTALFATURAMENTO,VARIACAOFAT,MESVARIADO,ANOVARIADO,CENARIOTIMISTACLIENTE,CENARIOPESSIMISTACLIENTE,
								MESFUTURO,ANOFUTURO,CENARIOTIMISTAFATURAMENTO,CENARIOPESSIMISTAFATURAMENTO,CENARIOPROVAVELFAT,CENARIOPROVAVELCLI,
								TIPO_PROCESSAMENTO,DATAPROCESSAMENTO,ITEM_REPROCESSADO)
								VALUES (IDDADOSFUTUROSGRUPO.NEXTVAL,IDITEM01,NOMEITEM01,QTDTOTCLIENTEMES01,TOTALCLIENTE01,VARIACAOCLI01,TOTALFATURAMENTO01,
								VARIACAOFAT01,MESVARIADO01,ANOVARIADO01,CENARIOTIMISTACLIENTE01,CENARIOPESSIMISTACLIENTE01,MESFUTURO01,ANOFUTURO01,CENARIOTIMISTAFATURAMENTO01,
								CENARIOPESSIMISTAFATURAMENTO01,CENARIOPROVAVELFAT01,CENARIOPROVAVELCLI01,1,(SELECT TO_CHAR (SYSDATE,'DD/MM/YYYY HH24:MM:SS') FROM DUAL),'S');						
								FETCH LISTA02 INTO IDITEM01,NOMEITEM01,QTDTOTCLIENTEMES01,TOTALCLIENTE01,VARIACAOCLI01,TOTALFATURAMENTO01,VARIACAOFAT01,
								MESVARIADO01,ANOVARIADO01,CENARIOTIMISTACLIENTE01,CENARIOPESSIMISTACLIENTE01,MESFUTURO01,ANOFUTURO01,CENARIOTIMISTAFATURAMENTO01,
								CENARIOPESSIMISTAFATURAMENTO01,CENARIOPROVAVELFAT01,CENARIOPROVAVELCLI01;	
						 END IF;
					END LOOP;
				CLOSE LISTA;
				CLOSE LISTA02;
			END;
	   END;


