CREATE OR REPLACE PROCEDURE SP_PROCESSADADOSGRUPO_TODOS (VALORPARAMETRO IN INT) AS
      BEGIN
	     DECLARE 					 
			IDITEM INT;
			NOMEITEM VARCHAR (100);
			QTDTOTCLIENTEMES FLOAT;
			TOTALCLIENTE FLOAT;
			VARIACAOCLI FLOAT;
			TOTALFATURAMENTO FLOAT;
			VARIACAOFAT FLOAT;
			MESVARIADO INT;
			ANOVARIADO INT;
			CENARIOTIMISTACLIENTE FLOAT;
			CENARIOPESSIMISTACLIENTE FLOAT;
			MESFUTURO INT;
			ANOFUTURO INT;			
			CENARIOTIMISTAFATURAMENTO FLOAT;
			CENARIOPESSIMISTAFATURAMENTO FLOAT;
			CENARIOPROVAVELFAT FLOAT;
			CENARIOPROVAVELCLI FLOAT;
			IDITEM01 INT;
			NOMEITEM01 VARCHAR (100);
			QTDTOTCLIENTEMES01 FLOAT;
			TOTALCLIENTE01 FLOAT;
			VARIACAOCLI01 FLOAT;
			TOTALFATURAMENTO01 FLOAT;
			VARIACAOFAT01 FLOAT;
			MESVARIADO01 INT;
			ANOVARIADO01 INT;
			CENARIOTIMISTACLIENTE01 FLOAT;
			CENARIOPESSIMISTACLIENTE01 FLOAT;
			MESFUTURO01 INT;
			ANOFUTURO01 INT;			
			CENARIOTIMISTAFATURAMENTO01 FLOAT;
			CENARIOPESSIMISTAFATURAMENTO01 FLOAT;
			CENARIOPROVAVELFAT01 FLOAT;
			CENARIOPROVAVELCLI01 FLOAT;			
			CONTADOR NUMBER := 0;
			TOTALCONT NUMBER;
			MESINSERIDO NUMBER := 0;
			ANOINSERIDO NUMBER := 0;
			CURSOR LISTA IS (SELECT IDCLASSE,NOMECLASSE,QTDTOTCLIENTEMES,TOTALCLIENTE,VARIACAOCLI,TOTALFATURAMENTO,VARIACAOFAT,
							 MES,ANO,CENARIOTIMISTACLIENTE,CENARIOPESSIMISTACLIENTE,MESFUTURO,ANOFUTURO,CENARIOTIMISTAFATURAMENTO,
							 CENARIOPESSIMISTAFATURAMENTO,CENARIOPROVAVELFAT,CENARIOPROVAVELCLI
							 FROM (
								SELECT
									C.ID_TIPO_CLASSE AS IDCLASSE,C.DESC_CLASSE AS NOMECLASSE,EXTRACT(MONTH FROM B.DT_REALIZADA) AS MES,EXTRACT(YEAR FROM B.DT_REALIZADA) AS ANO,
									SUM(B.QUANTCLIENTE) AS QTDTOTCLIENTEMES,
									(SELECT SUM (C.QUANTCLIENTE) FROM CARGA_DADOS C INNER JOIN ITEM D ON C.ITEM_IDITEM = D.ID_ITEM WHERE D.CLASSE_IDTIPO = C.ID_TIPO_CLASSE
									AND C.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-VALORPARAMETRO+1),'MONTH') AS DIA FROM CARGA_DADOS)) AS TOTALCLIENTE,
									TRUNC(((SUM(B.QUANTCLIENTE)/(SELECT SUM (C.QUANTCLIENTE) FROM CARGA_DADOS C INNER JOIN ITEM D ON C.ITEM_IDITEM = D.ID_ITEM 
									WHERE D.CLASSE_IDTIPO = C.ID_TIPO_CLASSE AND C.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-VALORPARAMETRO+1),'MONTH') AS DIA FROM CARGA_DADOS) GROUP BY D.CLASSE_IDTIPO))*100),2) AS VARIACAOCLI,
									SUM(B.QUANTFATURAMENTO) AS QTDTOTFATURAMENTOMES,
									(SELECT SUM (C.QUANTFATURAMENTO) FROM CARGA_DADOS C INNER JOIN ITEM D ON C.ITEM_IDITEM = D.ID_ITEM WHERE D.CLASSE_IDTIPO = C.ID_TIPO_CLASSE
									AND C.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-VALORPARAMETRO+1),'MONTH') AS DIA FROM CARGA_DADOS)) AS TOTALFATURAMENTO,
									TRUNC(((SUM(B.QUANTFATURAMENTO)/(SELECT SUM (C.QUANTFATURAMENTO) FROM CARGA_DADOS C INNER JOIN ITEM D ON C.ITEM_IDITEM = D.ID_ITEM 
									WHERE D.CLASSE_IDTIPO = C.ID_TIPO_CLASSE AND C.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-VALORPARAMETRO+1),'MONTH') AS DIA FROM CARGA_DADOS) GROUP BY D.CLASSE_IDTIPO))*100),2) AS VARIACAOFAT,
									EXTRACT (MONTH FROM (SELECT ADD_MONTHS(MAX(A.DT_REALIZADA),1) FROM CARGA_DADOS A INNER JOIN ITEM D ON A.ITEM_IDITEM = D.ID_ITEM 
									WHERE D.CLASSE_IDTIPO = C.ID_TIPO_CLASSE)) AS MESFUTURO,
									EXTRACT (YEAR FROM (SELECT ADD_MONTHS(MAX(A.DT_REALIZADA),1) FROM CARGA_DADOS A INNER JOIN ITEM D ON A.ITEM_IDITEM = D.ID_ITEM 
									WHERE D.CLASSE_IDTIPO = C.ID_TIPO_CLASSE)) AS ANOFUTURO,	
									(TRUNC(((SELECT MAX(VARIACAO) FROM (SELECT D.CLASSE_IDTIPO AS CLASSE,
									TRUNC(((SUM(A.QUANTCLIENTE)/(SELECT SUM (E.QUANTCLIENTE) FROM CARGA_DADOS E INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
									WHERE D.CLASSE_IDTIPO = F.CLASSE_IDTIPO AND E.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-VALORPARAMETRO+1),'MONTH') AS DIA FROM CARGA_DADOS)))*100),2) AS VARIACAO
									FROM CARGA_DADOS A INNER JOIN ITEM D ON D.ID_ITEM = A.ITEM_IDITEM
									GROUP BY D.CLASSE_IDTIPO, EXTRACT(MONTH FROM A.DT_REALIZADA),EXTRACT(YEAR FROM A.DT_REALIZADA)) WHERE CLASSE = C.ID_TIPO_CLASSE)
									*	
									(SELECT SUM (G.QUANTCLIENTE) FROM CARGA_DADOS G	INNER JOIN ITEM H ON G.ITEM_IDITEM = H.ID_ITEM
									WHERE EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																				INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																				WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																			 INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																			 WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND H.CLASSE_IDTIPO = C.ID_TIPO_CLASSE)/100),0) 
									+
									(SELECT SUM (G.QUANTCLIENTE) FROM CARGA_DADOS G	INNER JOIN ITEM H ON G.ITEM_IDITEM = H.ID_ITEM
									WHERE EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																				INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																				WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																			 INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																			 WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND H.CLASSE_IDTIPO = C.ID_TIPO_CLASSE)) AS CENARIOTIMISTACLIENTE,	
									(TRUNC(((SELECT MIN(VARIACAO) FROM (SELECT D.CLASSE_IDTIPO AS CLASSE,
									TRUNC(((SUM(A.QUANTCLIENTE)/(SELECT SUM (E.QUANTCLIENTE) FROM CARGA_DADOS E INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
									WHERE D.CLASSE_IDTIPO = F.CLASSE_IDTIPO AND E.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-VALORPARAMETRO+1),'MONTH') AS DIA FROM CARGA_DADOS)))*100),2) AS VARIACAO
									FROM CARGA_DADOS A INNER JOIN ITEM D ON D.ID_ITEM = A.ITEM_IDITEM
									GROUP BY D.CLASSE_IDTIPO, EXTRACT(MONTH FROM A.DT_REALIZADA),EXTRACT(YEAR FROM A.DT_REALIZADA)) WHERE CLASSE = C.ID_TIPO_CLASSE)
									*	
									(SELECT SUM (G.QUANTCLIENTE) FROM CARGA_DADOS G	INNER JOIN ITEM H ON G.ITEM_IDITEM = H.ID_ITEM
									WHERE EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																				INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																				WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																			 INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																			 WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND H.CLASSE_IDTIPO = C.ID_TIPO_CLASSE)/100),0) 
									+
									(SELECT SUM (G.QUANTCLIENTE) FROM CARGA_DADOS G	INNER JOIN ITEM H ON G.ITEM_IDITEM = H.ID_ITEM
									WHERE EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																				INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																				WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																			 INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																			 WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND H.CLASSE_IDTIPO = C.ID_TIPO_CLASSE)) AS CENARIOPESSIMISTACLIENTE,	
									(TRUNC(((SELECT MAX(VARIACAO) FROM (SELECT D.CLASSE_IDTIPO AS CLASSE,
									TRUNC(((SUM(A.QUANTFATURAMENTO)/(SELECT SUM (E.QUANTFATURAMENTO) FROM CARGA_DADOS E INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
									WHERE D.CLASSE_IDTIPO = F.CLASSE_IDTIPO AND E.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-VALORPARAMETRO+1),'MONTH') AS DIA FROM CARGA_DADOS)))*100),2) AS VARIACAO
									FROM CARGA_DADOS A INNER JOIN ITEM D ON D.ID_ITEM = A.ITEM_IDITEM
									GROUP BY D.CLASSE_IDTIPO, EXTRACT(MONTH FROM A.DT_REALIZADA),EXTRACT(YEAR FROM A.DT_REALIZADA)) WHERE CLASSE = C.ID_TIPO_CLASSE)
									*	
									(SELECT SUM (G.QUANTFATURAMENTO) FROM CARGA_DADOS G	INNER JOIN ITEM H ON G.ITEM_IDITEM = H.ID_ITEM
									WHERE EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																				INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																				WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																			 INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																			 WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND H.CLASSE_IDTIPO = C.ID_TIPO_CLASSE)/100),0) 
									+
									(SELECT SUM (G.QUANTFATURAMENTO) FROM CARGA_DADOS G	INNER JOIN ITEM H ON G.ITEM_IDITEM = H.ID_ITEM
									WHERE EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																				INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																				WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																			 INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																			 WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND H.CLASSE_IDTIPO = C.ID_TIPO_CLASSE)) AS CENARIOTIMISTAFATURAMENTO,	
									(TRUNC(((SELECT MIN(VARIACAO) FROM (SELECT D.CLASSE_IDTIPO AS CLASSE,
									TRUNC(((SUM(A.QUANTFATURAMENTO)/(SELECT SUM (E.QUANTFATURAMENTO) FROM CARGA_DADOS E INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
									WHERE D.CLASSE_IDTIPO = F.CLASSE_IDTIPO AND E.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-VALORPARAMETRO+1),'MONTH') AS DIA FROM CARGA_DADOS)))*100),2) AS VARIACAO
									FROM CARGA_DADOS A INNER JOIN ITEM D ON D.ID_ITEM = A.ITEM_IDITEM
									GROUP BY D.CLASSE_IDTIPO, EXTRACT(MONTH FROM A.DT_REALIZADA),EXTRACT(YEAR FROM A.DT_REALIZADA)) WHERE CLASSE = C.ID_TIPO_CLASSE)
									*	
									(SELECT SUM (G.QUANTFATURAMENTO) FROM CARGA_DADOS G	INNER JOIN ITEM H ON G.ITEM_IDITEM = H.ID_ITEM
									WHERE EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																				INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																				WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																			 INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																			 WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND H.CLASSE_IDTIPO = C.ID_TIPO_CLASSE)/100),0) 
									+
									(SELECT SUM (G.QUANTFATURAMENTO) FROM CARGA_DADOS G	INNER JOIN ITEM H ON G.ITEM_IDITEM = H.ID_ITEM
									WHERE EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																				INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																				WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																			 INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																			 WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND H.CLASSE_IDTIPO = C.ID_TIPO_CLASSE)) AS CENARIOPESSIMISTAFATURAMENTO,									
									(SELECT REGRESSAO FROM( SELECT TRUNC(REGR_INTERCEPT(SUM(B.QUANTFATURAMENTO), EXTRACT(MONTH FROM B.DT_REALIZADA) + 1) 
													OVER (PARTITION BY C.CLASSE_IDTIPO),2) AS REGRESSAO,C.CLASSE_IDTIPO AS CLASSE  
											 FROM CARGA_DADOS B
											 INNER JOIN ITEM C ON B.ITEM_IDITEM = C.ID_ITEM
											 WHERE B.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-5),'MONTH') AS DIA FROM CARGA_DADOS) 											 										 
											 GROUP BY C.CLASSE_IDTIPO,EXTRACT(YEAR FROM B.DT_REALIZADA),EXTRACT(MONTH FROM B.DT_REALIZADA)
											) WHERE ROWNUM = 1 AND CLASSE = C.ID_TIPO_CLASSE	
									) AS CENARIOPROVAVELFAT,
									(SELECT REGRESSAO FROM( SELECT TRUNC(REGR_INTERCEPT(SUM(B.QUANTCLIENTE), EXTRACT(MONTH FROM B.DT_REALIZADA) + 1) 
											OVER (PARTITION BY C.CLASSE_IDTIPO),2) AS REGRESSAO,C.CLASSE_IDTIPO AS CLASSE  
										FROM CARGA_DADOS B
										INNER JOIN ITEM C ON B.ITEM_IDITEM = C.ID_ITEM
										WHERE B.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-5),'MONTH') AS DIA FROM CARGA_DADOS) 										
										GROUP BY C.CLASSE_IDTIPO,EXTRACT(YEAR FROM B.DT_REALIZADA),EXTRACT(MONTH FROM B.DT_REALIZADA)
									  ) WHERE ROWNUM = 1 AND CLASSE = C.ID_TIPO_CLASSE	
									) AS CENARIOPROVAVELCLI										
									
								FROM ITEM A 
								INNER JOIN CARGA_DADOS B ON A.ID_ITEM = B.ITEM_IDITEM
								INNER JOIN TIPOCLASSE C ON A.CLASSE_IDTIPO = C.ID_TIPO_CLASSE
								WHERE B.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-VALORPARAMETRO+1),'MONTH') AS DIA FROM CARGA_DADOS)
								GROUP BY C.ID_TIPO_CLASSE,C.DESC_CLASSE,EXTRACT(MONTH FROM B.DT_REALIZADA),EXTRACT(YEAR FROM B.DT_REALIZADA)
								ORDER BY 2,4,3)
								WHERE VARIACAOCLI = (SELECT MAX(VARIACAO) FROM (SELECT D.CLASSE_IDTIPO AS CLASSE,
								TRUNC(((SUM(A.QUANTCLIENTE)/(SELECT SUM (E.QUANTCLIENTE) FROM CARGA_DADOS E INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
								WHERE D.CLASSE_IDTIPO = F.CLASSE_IDTIPO AND E.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-VALORPARAMETRO+1),'MONTH') AS DIA FROM CARGA_DADOS)))*100),2) AS VARIACAO
								FROM CARGA_DADOS A INNER JOIN ITEM D ON D.ID_ITEM = A.ITEM_IDITEM
								GROUP BY D.CLASSE_IDTIPO, EXTRACT(MONTH FROM A.DT_REALIZADA),EXTRACT(YEAR FROM A.DT_REALIZADA)) WHERE CLASSE = IDCLASSE));
								
								
				
			CURSOR LISTA02 IS (SELECT IDCLASSE,NOMECLASSE,QTDTOTCLIENTEMES,TOTALCLIENTE,VARIACAOCLI,TOTALFATURAMENTO,VARIACAOFAT,
							   MES,ANO,CENARIOTIMISTACLIENTE,CENARIOPESSIMISTACLIENTE,MESFUTURO,ANOFUTURO,CENARIOTIMISTAFATURAMENTO,
							   CENARIOPESSIMISTAFATURAMENTO,CENARIOPROVAVELFAT,CENARIOPROVAVELCLI
							   FROM (SELECT
									C.ID_TIPO_CLASSE AS IDCLASSE,C.DESC_CLASSE AS NOMECLASSE,EXTRACT(MONTH FROM B.DT_REALIZADA) AS MES,EXTRACT(YEAR FROM B.DT_REALIZADA) AS ANO,
									SUM(B.QUANTCLIENTE) AS QTDTOTCLIENTEMES,
									(SELECT SUM (C.QUANTCLIENTE) FROM CARGA_DADOS C INNER JOIN ITEM D ON C.ITEM_IDITEM = D.ID_ITEM WHERE D.CLASSE_IDTIPO = C.ID_TIPO_CLASSE
									AND EXTRACT(DAY FROM C.DT_REALIZADA) BETWEEN 1 AND 15 
									AND C.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-VALORPARAMETRO+1),'MONTH') AS DIA FROM CARGA_DADOS)) AS TOTALCLIENTE,
									TRUNC(((SUM(B.QUANTCLIENTE)/(SELECT SUM (C.QUANTCLIENTE) FROM CARGA_DADOS C INNER JOIN ITEM D ON C.ITEM_IDITEM = D.ID_ITEM 
									WHERE D.CLASSE_IDTIPO = C.ID_TIPO_CLASSE 
									AND EXTRACT(DAY FROM C.DT_REALIZADA) BETWEEN 1 AND 15 
									AND C.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-VALORPARAMETRO+1),'MONTH') AS DIA FROM CARGA_DADOS) GROUP BY D.CLASSE_IDTIPO))*100),2) AS VARIACAOCLI,
									SUM(B.QUANTFATURAMENTO) AS QTDTOTFATURAMENTOMES,
									(SELECT SUM (C.QUANTFATURAMENTO) FROM CARGA_DADOS C INNER JOIN ITEM D ON C.ITEM_IDITEM = D.ID_ITEM WHERE D.CLASSE_IDTIPO = C.ID_TIPO_CLASSE
									AND EXTRACT(DAY FROM C.DT_REALIZADA) BETWEEN 1 AND 15 
									AND C.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-VALORPARAMETRO+1),'MONTH') AS DIA FROM CARGA_DADOS)) AS TOTALFATURAMENTO,
									TRUNC(((SUM(B.QUANTFATURAMENTO)/(SELECT SUM (C.QUANTFATURAMENTO) FROM CARGA_DADOS C INNER JOIN ITEM D ON C.ITEM_IDITEM = D.ID_ITEM 
									WHERE D.CLASSE_IDTIPO = C.ID_TIPO_CLASSE 
									AND EXTRACT(DAY FROM C.DT_REALIZADA) BETWEEN 1 AND 15 
									AND C.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-VALORPARAMETRO+1),'MONTH') AS DIA FROM CARGA_DADOS) GROUP BY D.CLASSE_IDTIPO))*100),2) AS VARIACAOFAT,
									EXTRACT (MONTH FROM (SELECT ADD_MONTHS(MAX(A.DT_REALIZADA),1) FROM CARGA_DADOS A INNER JOIN ITEM D ON A.ITEM_IDITEM = D.ID_ITEM 
									WHERE D.CLASSE_IDTIPO = C.ID_TIPO_CLASSE)) AS MESFUTURO,
									EXTRACT (YEAR FROM (SELECT ADD_MONTHS(MAX(A.DT_REALIZADA),1) FROM CARGA_DADOS A INNER JOIN ITEM D ON A.ITEM_IDITEM = D.ID_ITEM 
									WHERE D.CLASSE_IDTIPO = C.ID_TIPO_CLASSE)) AS ANOFUTURO,	
									(TRUNC(((SELECT MAX(VARIACAO) FROM (SELECT D.CLASSE_IDTIPO AS CLASSE,
									TRUNC(((SUM(A.QUANTCLIENTE)/(SELECT SUM (E.QUANTCLIENTE) FROM CARGA_DADOS E INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
									WHERE D.CLASSE_IDTIPO = F.CLASSE_IDTIPO 
									AND EXTRACT(DAY FROM E.DT_REALIZADA) BETWEEN 1 AND 15 
									AND E.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-VALORPARAMETRO+1),'MONTH') AS DIA FROM CARGA_DADOS)))*100),2) AS VARIACAO
									FROM CARGA_DADOS A INNER JOIN ITEM D ON D.ID_ITEM = A.ITEM_IDITEM
									WHERE EXTRACT(DAY FROM A.DT_REALIZADA) BETWEEN 1 AND 15 	
									GROUP BY D.CLASSE_IDTIPO, EXTRACT(MONTH FROM A.DT_REALIZADA),EXTRACT(YEAR FROM A.DT_REALIZADA)) WHERE CLASSE = C.ID_TIPO_CLASSE)
									*	
									(SELECT SUM (G.QUANTCLIENTE) FROM CARGA_DADOS G	INNER JOIN ITEM H ON G.ITEM_IDITEM = H.ID_ITEM
									WHERE EXTRACT(DAY FROM G.DT_REALIZADA) BETWEEN 1 AND 15									
									AND EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																				INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																				WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																			 INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																			 WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND H.CLASSE_IDTIPO = C.ID_TIPO_CLASSE)/100),0) 
									+
									(SELECT SUM (G.QUANTCLIENTE) FROM CARGA_DADOS G	INNER JOIN ITEM H ON G.ITEM_IDITEM = H.ID_ITEM
									WHERE EXTRACT(DAY FROM G.DT_REALIZADA) BETWEEN 1 AND 15 									
									AND EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																				INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																				WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																			 INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																			 WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND H.CLASSE_IDTIPO = C.ID_TIPO_CLASSE)) AS CENARIOTIMISTACLIENTE,	
									(TRUNC(((SELECT MIN(VARIACAO) FROM (SELECT D.CLASSE_IDTIPO AS CLASSE,
									TRUNC(((SUM(A.QUANTCLIENTE)/(SELECT SUM (E.QUANTCLIENTE) FROM CARGA_DADOS E INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
									WHERE D.CLASSE_IDTIPO = F.CLASSE_IDTIPO 
									AND EXTRACT(DAY FROM E.DT_REALIZADA) BETWEEN 1 AND 15 	
									AND E.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-VALORPARAMETRO+1),'MONTH') AS DIA FROM CARGA_DADOS)))*100),2) AS VARIACAO
									FROM CARGA_DADOS A INNER JOIN ITEM D ON D.ID_ITEM = A.ITEM_IDITEM
									WHERE EXTRACT(DAY FROM A.DT_REALIZADA) BETWEEN 1 AND 15 	
									GROUP BY D.CLASSE_IDTIPO, EXTRACT(MONTH FROM A.DT_REALIZADA),EXTRACT(YEAR FROM A.DT_REALIZADA)) WHERE CLASSE = C.ID_TIPO_CLASSE)
									*	
									(SELECT SUM (G.QUANTCLIENTE) FROM CARGA_DADOS G	INNER JOIN ITEM H ON G.ITEM_IDITEM = H.ID_ITEM
									WHERE EXTRACT(DAY FROM G.DT_REALIZADA) BETWEEN 1 AND 15 	
									AND EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																				INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																				WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																			 INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																			 WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND H.CLASSE_IDTIPO = C.ID_TIPO_CLASSE)/100),0) 
									+
									(SELECT SUM (G.QUANTCLIENTE) FROM CARGA_DADOS G	INNER JOIN ITEM H ON G.ITEM_IDITEM = H.ID_ITEM
									WHERE EXTRACT(DAY FROM G.DT_REALIZADA) BETWEEN 1 AND 15 	
									AND EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																				INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																				WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																			 INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																			 WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND H.CLASSE_IDTIPO = C.ID_TIPO_CLASSE)) AS CENARIOPESSIMISTACLIENTE,	
									(TRUNC(((SELECT MAX(VARIACAO) FROM (SELECT D.CLASSE_IDTIPO AS CLASSE,
									TRUNC(((SUM(A.QUANTFATURAMENTO)/(SELECT SUM (E.QUANTFATURAMENTO) FROM CARGA_DADOS E INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
									WHERE D.CLASSE_IDTIPO = F.CLASSE_IDTIPO
									AND EXTRACT(DAY FROM E.DT_REALIZADA) BETWEEN 1 AND 15 	
									AND E.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-VALORPARAMETRO+1),'MONTH') AS DIA FROM CARGA_DADOS)))*100),2) AS VARIACAO
									FROM CARGA_DADOS A INNER JOIN ITEM D ON D.ID_ITEM = A.ITEM_IDITEM
									WHERE EXTRACT(DAY FROM A.DT_REALIZADA) BETWEEN 1 AND 15 	
									GROUP BY D.CLASSE_IDTIPO, EXTRACT(MONTH FROM A.DT_REALIZADA),EXTRACT(YEAR FROM A.DT_REALIZADA)) WHERE CLASSE = C.ID_TIPO_CLASSE)
									*	
									(SELECT SUM (G.QUANTFATURAMENTO) FROM CARGA_DADOS G	INNER JOIN ITEM H ON G.ITEM_IDITEM = H.ID_ITEM
									WHERE EXTRACT(DAY FROM G.DT_REALIZADA) BETWEEN 1 AND 15 	
									AND EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																				INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																				WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																			 INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																			 WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND H.CLASSE_IDTIPO = C.ID_TIPO_CLASSE)/100),0) 
									+
									(SELECT SUM (G.QUANTFATURAMENTO) FROM CARGA_DADOS G	INNER JOIN ITEM H ON G.ITEM_IDITEM = H.ID_ITEM
									WHERE EXTRACT(DAY FROM G.DT_REALIZADA) BETWEEN 1 AND 15 	
									AND EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																				INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																				WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																			 INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																			 WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND H.CLASSE_IDTIPO = C.ID_TIPO_CLASSE)) AS CENARIOTIMISTAFATURAMENTO,	
									(TRUNC(((SELECT MIN(VARIACAO) FROM (SELECT D.CLASSE_IDTIPO AS CLASSE,
									TRUNC(((SUM(A.QUANTFATURAMENTO)/(SELECT SUM (E.QUANTFATURAMENTO) FROM CARGA_DADOS E INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
									WHERE D.CLASSE_IDTIPO = F.CLASSE_IDTIPO
                                    AND EXTRACT(DAY FROM E.DT_REALIZADA) BETWEEN 1 AND 15 	
									AND E.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-VALORPARAMETRO+1),'MONTH') AS DIA FROM CARGA_DADOS)))*100),2) AS VARIACAO
									FROM CARGA_DADOS A INNER JOIN ITEM D ON D.ID_ITEM = A.ITEM_IDITEM
									WHERE EXTRACT(DAY FROM A.DT_REALIZADA) BETWEEN 1 AND 15 	
									GROUP BY D.CLASSE_IDTIPO, EXTRACT(MONTH FROM A.DT_REALIZADA),EXTRACT(YEAR FROM A.DT_REALIZADA)) WHERE CLASSE = C.ID_TIPO_CLASSE)
									*	
									(SELECT SUM (G.QUANTFATURAMENTO) FROM CARGA_DADOS G	INNER JOIN ITEM H ON G.ITEM_IDITEM = H.ID_ITEM
									WHERE EXTRACT(DAY FROM G.DT_REALIZADA) BETWEEN 1 AND 15 	
									AND EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																				INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																				WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																			 INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																			 WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND H.CLASSE_IDTIPO = C.ID_TIPO_CLASSE)/100),0) 
									+
									(SELECT SUM (G.QUANTFATURAMENTO) FROM CARGA_DADOS G	INNER JOIN ITEM H ON G.ITEM_IDITEM = H.ID_ITEM
									WHERE EXTRACT(DAY FROM G.DT_REALIZADA) BETWEEN 1 AND 15 	
									AND EXTRACT(MONTH FROM G.DT_REALIZADA) = (SELECT EXTRACT(MONTH FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																				INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																				WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND EXTRACT(YEAR FROM G.DT_REALIZADA) = (SELECT EXTRACT(YEAR FROM MAX(E.DT_REALIZADA)) FROM CARGA_DADOS E 
																			 INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
																			 WHERE F.CLASSE_IDTIPO = H.CLASSE_IDTIPO)
									AND H.CLASSE_IDTIPO = C.ID_TIPO_CLASSE)) AS CENARIOPESSIMISTAFATURAMENTO,
								   	(SELECT REGRESSAO FROM( SELECT TRUNC(REGR_INTERCEPT(SUM(B.QUANTFATURAMENTO), EXTRACT(MONTH FROM B.DT_REALIZADA) + 1) 
													OVER (PARTITION BY C.CLASSE_IDTIPO),2) AS REGRESSAO,C.CLASSE_IDTIPO AS CLASSE  
											 FROM CARGA_DADOS B
											 INNER JOIN ITEM C ON B.ITEM_IDITEM = C.ID_ITEM
											 WHERE B.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-5),'MONTH') AS DIA FROM CARGA_DADOS) 
											 AND EXTRACT(DAY FROM B.DT_REALIZADA) BETWEEN 1 AND 15											 
											 GROUP BY C.CLASSE_IDTIPO,EXTRACT(YEAR FROM B.DT_REALIZADA),EXTRACT(MONTH FROM B.DT_REALIZADA)
											) WHERE ROWNUM = 1 AND CLASSE = C.ID_TIPO_CLASSE	
									) AS CENARIOPROVAVELFAT,
									(SELECT REGRESSAO FROM( SELECT TRUNC(REGR_INTERCEPT(SUM(B.QUANTCLIENTE), EXTRACT(MONTH FROM B.DT_REALIZADA) + 1) 
											OVER (PARTITION BY C.CLASSE_IDTIPO),2) AS REGRESSAO,C.CLASSE_IDTIPO AS CLASSE  
										FROM CARGA_DADOS B
										INNER JOIN ITEM C ON B.ITEM_IDITEM = C.ID_ITEM
										WHERE B.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-5),'MONTH') AS DIA FROM CARGA_DADOS) 
										AND EXTRACT(DAY FROM B.DT_REALIZADA) BETWEEN 1 AND 15
										GROUP BY C.CLASSE_IDTIPO,EXTRACT(YEAR FROM B.DT_REALIZADA),EXTRACT(MONTH FROM B.DT_REALIZADA)
									  ) WHERE ROWNUM = 1 AND CLASSE = C.ID_TIPO_CLASSE	
									) AS CENARIOPROVAVELCLI										 
									
								FROM ITEM A 
								INNER JOIN CARGA_DADOS B ON A.ID_ITEM = B.ITEM_IDITEM
								INNER JOIN TIPOCLASSE C ON A.CLASSE_IDTIPO = C.ID_TIPO_CLASSE
								WHERE B.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-VALORPARAMETRO+1),'MONTH') AS DIA FROM CARGA_DADOS)
								AND EXTRACT(DAY FROM B.DT_REALIZADA) BETWEEN 1 AND 15 
								GROUP BY C.ID_TIPO_CLASSE,C.DESC_CLASSE,EXTRACT(MONTH FROM B.DT_REALIZADA),EXTRACT(YEAR FROM B.DT_REALIZADA)
								ORDER BY 2,4,3)
								
								WHERE VARIACAOCLI = (SELECT MAX(VARIACAO) FROM (SELECT D.CLASSE_IDTIPO AS CLASSE,
								TRUNC(((SUM(A.QUANTCLIENTE)/(SELECT SUM (E.QUANTCLIENTE) FROM CARGA_DADOS E INNER JOIN ITEM F ON E.ITEM_IDITEM = F.ID_ITEM
								WHERE D.CLASSE_IDTIPO = F.CLASSE_IDTIPO 
								AND EXTRACT(DAY FROM E.DT_REALIZADA) BETWEEN 1 AND 15 
								AND E.DT_REALIZADA >= (SELECT TRUNC(ADD_MONTHS(MAX(DT_REALIZADA),-VALORPARAMETRO+1),'MONTH') AS DIA FROM CARGA_DADOS)))*100),2) AS VARIACAO
								FROM CARGA_DADOS A INNER JOIN ITEM D ON D.ID_ITEM = A.ITEM_IDITEM
								WHERE EXTRACT(DAY FROM A.DT_REALIZADA) BETWEEN 1 AND 15 
								GROUP BY D.CLASSE_IDTIPO, EXTRACT(MONTH FROM A.DT_REALIZADA),EXTRACT(YEAR FROM A.DT_REALIZADA)) WHERE CLASSE = IDCLASSE));						
								
								
			BEGIN
                SELECT COUNT(*) INTO TOTALCONT FROM (SELECT B.CLASSE_IDTIPO FROM CARGA_DADOS A 
													 INNER JOIN ITEM B ON A.ITEM_IDITEM = B.ID_ITEM
													 GROUP BY B.CLASSE_IDTIPO);
				SELECT COALESCE(MES,0) INTO MESINSERIDO FROM (SELECT MAX(MESFUTURO) AS MES FROM DADOS_FUTUROS_GRUPO);
				SELECT COALESCE(ANO,0) INTO ANOINSERIDO FROM (SELECT MAX(ANOFUTURO) AS ANO FROM DADOS_FUTUROS_GRUPO);				
				DBMS_OUTPUT.ENABLE (100000000);				
				OPEN LISTA;				
				FETCH LISTA INTO IDITEM,NOMEITEM,QTDTOTCLIENTEMES,TOTALCLIENTE,VARIACAOCLI,TOTALFATURAMENTO,VARIACAOFAT,
				MESVARIADO,ANOVARIADO,CENARIOTIMISTACLIENTE,CENARIOPESSIMISTACLIENTE,MESFUTURO,ANOFUTURO,CENARIOTIMISTAFATURAMENTO,
				CENARIOPESSIMISTAFATURAMENTO,CENARIOPROVAVELFAT,CENARIOPROVAVELCLI;
				OPEN LISTA02;				
				FETCH LISTA02 INTO IDITEM01,NOMEITEM01,QTDTOTCLIENTEMES01,TOTALCLIENTE01,VARIACAOCLI01,TOTALFATURAMENTO01,VARIACAOFAT01,
				MESVARIADO01,ANOVARIADO01,CENARIOTIMISTACLIENTE01,CENARIOPESSIMISTACLIENTE01,MESFUTURO01,ANOFUTURO01,CENARIOTIMISTAFATURAMENTO01,
				CENARIOPESSIMISTAFATURAMENTO01,CENARIOPROVAVELFAT01,CENARIOPROVAVELCLI01;
				WHILE CONTADOR < TOTALCONT
					LOOP 			
						 IF (MESFUTURO <> MESINSERIDO AND ANOFUTURO <> ANOINSERIDO) THEN
								CONTADOR := CONTADOR + 1;
								INSERT INTO DADOS_FUTUROS_GRUPO (ID_DADOS_FUTUROS_GRUPO,ID_GRUPO,NOME_GRUPO,QTDTOTCLIENTEMES,TOTALCLIENTE,
								VARIACAOCLI,TOTALFATURAMENTO,VARIACAOFAT,MESVARIADO,ANOVARIADO,CENARIOTIMISTACLIENTE,CENARIOPESSIMISTACLIENTE,
								MESFUTURO,ANOFUTURO,CENARIOTIMISTAFATURAMENTO,CENARIOPESSIMISTAFATURAMENTO,CENARIOPROVAVELFAT,CENARIOPROVAVELCLI,
								TIPO_PROCESSAMENTO,ITEM_REPROCESSADO)
								VALUES (IDDADOSFUTUROSGRUPO.NEXTVAL,IDITEM,NOMEITEM,QTDTOTCLIENTEMES,TOTALCLIENTE,VARIACAOCLI,TOTALFATURAMENTO,
								VARIACAOFAT,MESVARIADO,ANOVARIADO,CENARIOTIMISTACLIENTE,CENARIOPESSIMISTACLIENTE,MESFUTURO,ANOFUTURO,CENARIOTIMISTAFATURAMENTO,
								CENARIOPESSIMISTAFATURAMENTO,CENARIOPROVAVELFAT,CENARIOPROVAVELCLI,2,'N');						
								FETCH LISTA INTO IDITEM,NOMEITEM,QTDTOTCLIENTEMES,TOTALCLIENTE,VARIACAOCLI,TOTALFATURAMENTO,VARIACAOFAT,
								MESVARIADO,ANOVARIADO,CENARIOTIMISTACLIENTE,CENARIOPESSIMISTACLIENTE,MESFUTURO,ANOFUTURO,CENARIOTIMISTAFATURAMENTO,
								CENARIOPESSIMISTAFATURAMENTO,CENARIOPROVAVELFAT,CENARIOPROVAVELCLI;
								
								INSERT INTO DADOS_FUTUROS_GRUPO (ID_DADOS_FUTUROS_GRUPO,ID_GRUPO,NOME_GRUPO,QTDTOTCLIENTEMES,TOTALCLIENTE,
								VARIACAOCLI,TOTALFATURAMENTO,VARIACAOFAT,MESVARIADO,ANOVARIADO,CENARIOTIMISTACLIENTE,CENARIOPESSIMISTACLIENTE,
								MESFUTURO,ANOFUTURO,CENARIOTIMISTAFATURAMENTO,CENARIOPESSIMISTAFATURAMENTO,CENARIOPROVAVELFAT,CENARIOPROVAVELCLI,
								TIPO_PROCESSAMENTO,ITEM_REPROCESSADO)
								VALUES (IDDADOSFUTUROSGRUPO.NEXTVAL,IDITEM01,NOMEITEM01,QTDTOTCLIENTEMES01,TOTALCLIENTE01,VARIACAOCLI01,TOTALFATURAMENTO01,
								VARIACAOFAT01,MESVARIADO01,ANOVARIADO01,CENARIOTIMISTACLIENTE01,CENARIOPESSIMISTACLIENTE01,MESFUTURO01,ANOFUTURO01,CENARIOTIMISTAFATURAMENTO01,
								CENARIOPESSIMISTAFATURAMENTO01,CENARIOPROVAVELFAT01,CENARIOPROVAVELCLI01,1,'N');						
								FETCH LISTA02 INTO IDITEM01,NOMEITEM01,QTDTOTCLIENTEMES01,TOTALCLIENTE01,VARIACAOCLI01,TOTALFATURAMENTO01,VARIACAOFAT01,
								MESVARIADO01,ANOVARIADO01,CENARIOTIMISTACLIENTE01,CENARIOPESSIMISTACLIENTE01,MESFUTURO01,ANOFUTURO01,CENARIOTIMISTAFATURAMENTO01,
								CENARIOPESSIMISTAFATURAMENTO01,CENARIOPROVAVELFAT01,CENARIOPROVAVELCLI01;								
						 ELSE
								CONTADOR := CONTADOR + 1;
								INSERT INTO DADOS_FUTUROS_GRUPO (ID_DADOS_FUTUROS_GRUPO,ID_GRUPO,NOME_GRUPO,QTDTOTCLIENTEMES,TOTALCLIENTE,
								VARIACAOCLI,TOTALFATURAMENTO,VARIACAOFAT,MESVARIADO,ANOVARIADO,CENARIOTIMISTACLIENTE,CENARIOPESSIMISTACLIENTE,
								MESFUTURO,ANOFUTURO,CENARIOTIMISTAFATURAMENTO,CENARIOPESSIMISTAFATURAMENTO,CENARIOPROVAVELFAT,CENARIOPROVAVELCLI,
								TIPO_PROCESSAMENTO,ITEM_REPROCESSADO)
								VALUES (IDDADOSFUTUROSGRUPO.NEXTVAL,IDITEM,NOMEITEM,QTDTOTCLIENTEMES,TOTALCLIENTE,VARIACAOCLI,TOTALFATURAMENTO,
								VARIACAOFAT,MESVARIADO,ANOVARIADO,CENARIOTIMISTACLIENTE,CENARIOPESSIMISTACLIENTE,MESFUTURO,ANOFUTURO,CENARIOTIMISTAFATURAMENTO,
								CENARIOPESSIMISTAFATURAMENTO,CENARIOPROVAVELFAT,CENARIOPROVAVELCLI,2,'S');						
								FETCH LISTA INTO IDITEM,NOMEITEM,QTDTOTCLIENTEMES,TOTALCLIENTE,VARIACAOCLI,TOTALFATURAMENTO,VARIACAOFAT,
								MESVARIADO,ANOVARIADO,CENARIOTIMISTACLIENTE,CENARIOPESSIMISTACLIENTE,MESFUTURO,ANOFUTURO,CENARIOTIMISTAFATURAMENTO,
								CENARIOPESSIMISTAFATURAMENTO,CENARIOPROVAVELFAT,CENARIOPROVAVELCLI;
								
								INSERT INTO DADOS_FUTUROS_GRUPO (ID_DADOS_FUTUROS_GRUPO,ID_GRUPO,NOME_GRUPO,QTDTOTCLIENTEMES,TOTALCLIENTE,
								VARIACAOCLI,TOTALFATURAMENTO,VARIACAOFAT,MESVARIADO,ANOVARIADO,CENARIOTIMISTACLIENTE,CENARIOPESSIMISTACLIENTE,
								MESFUTURO,ANOFUTURO,CENARIOTIMISTAFATURAMENTO,CENARIOPESSIMISTAFATURAMENTO,CENARIOPROVAVELFAT,CENARIOPROVAVELCLI,
								TIPO_PROCESSAMENTO,ITEM_REPROCESSADO)
								VALUES (IDDADOSFUTUROSGRUPO.NEXTVAL,IDITEM01,NOMEITEM01,QTDTOTCLIENTEMES01,TOTALCLIENTE01,VARIACAOCLI01,TOTALFATURAMENTO01,
								VARIACAOFAT01,MESVARIADO01,ANOVARIADO01,CENARIOTIMISTACLIENTE01,CENARIOPESSIMISTACLIENTE01,MESFUTURO01,ANOFUTURO01,CENARIOTIMISTAFATURAMENTO01,
								CENARIOPESSIMISTAFATURAMENTO01,CENARIOPROVAVELFAT01,CENARIOPROVAVELCLI01,1,'S');						
								FETCH LISTA02 INTO IDITEM01,NOMEITEM01,QTDTOTCLIENTEMES01,TOTALCLIENTE01,VARIACAOCLI01,TOTALFATURAMENTO01,VARIACAOFAT01,
								MESVARIADO01,ANOVARIADO01,CENARIOTIMISTACLIENTE01,CENARIOPESSIMISTACLIENTE01,MESFUTURO01,ANOFUTURO01,CENARIOTIMISTAFATURAMENTO01,
								CENARIOPESSIMISTAFATURAMENTO01,CENARIOPROVAVELFAT01,CENARIOPROVAVELCLI01;	
						 END IF;
					END LOOP;
				CLOSE LISTA;
				CLOSE LISTA02;
			END;
	   END;


